// Таблица "3 специализации -> название класса" ArcheAge.
// Источник — реальный HTML калькулятора archeagecodex.com/ru/calc/
// (атрибуты data-proflist="id1,id2,id3" -> текст названия, id переведены в
// наши строковые id специализаций по data-clid из того же калькулятора).
// Ключ — id специализаций через "+" в алфавитном порядке (см.
// specializationsData.ts). Заполнено 364 из 364
// возможных сочетаний (C(14,3), специализаций всего 14 — считая "Стрельбу"
// и "Танец", которые дают вариации уже существующих имён).
export const CLASS_NAME_BY_COMBO: Record<string, string> = {
  "gipnoz+gnev+isceleine": "Врачеватель",
  "gipnoz+gnev+kovarstvo": "Захватчик",
  "gipnoz+gnev+misticizm": "Духовидец",
  "gipnoz+gnev+napadenie": "Экзекутор",
  "gipnoz+gnev+oborona": "Воитель",
  "gipnoz+gnev+presledovanie": "Секутор",
  "gipnoz+gnev+skritnost": "Чаромант",
  "gipnoz+gnev+soprotivlenie": "Прокуратор",
  "gipnoz+gnev+strelba": "Бандит",
  "gipnoz+gnev+tanec": "Яростный иллюзионист",
  "gipnoz+gnev+volshebstvo": "Адепт",
  "gipnoz+gnev+voodush": "Кардинал",
  "gipnoz+isceleine+kovarstvo": "Иезуит",
  "gipnoz+isceleine+misticizm": "Отступник",
  "gipnoz+isceleine+napadenie": "Законник",
  "gipnoz+isceleine+oborona": "Проповедник",
  "gipnoz+isceleine+presledovanie": "Знахарь",
  "gipnoz+isceleine+skritnost": "Фаталист",
  "gipnoz+isceleine+soprotivlenie": "Аскет",
  "gipnoz+isceleine+strelba": "Магнетизер",
  "gipnoz+isceleine+tanec": "Великодушный иллюзионист",
  "gipnoz+isceleine+volshebstvo": "Исповедник",
  "gipnoz+isceleine+voodush": "Клирик",
  "gipnoz+kovarstvo+misticizm": "Иллюминат",
  "gipnoz+kovarstvo+napadenie": "Покоритель",
  "gipnoz+kovarstvo+oborona": "Апокалиптик",
  "gipnoz+kovarstvo+presledovanie": "Искуситель",
  "gipnoz+kovarstvo+skritnost": "Морок",
  "gipnoz+kovarstvo+soprotivlenie": "Психокинетик",
  "gipnoz+kovarstvo+strelba": "Гипнолог",
  "gipnoz+kovarstvo+tanec": "Бесстрастный иерофант",
  "gipnoz+kovarstvo+volshebstvo": "Варлок",
  "gipnoz+kovarstvo+voodush": "Бунтарь",
  "gipnoz+misticizm+napadenie": "Чернокнижник",
  "gipnoz+misticizm+oborona": "Мистификатор",
  "gipnoz+misticizm+presledovanie": "Зверолов",
  "gipnoz+misticizm+skritnost": "Ликвидатор",
  "gipnoz+misticizm+soprotivlenie": "Иллюзионист",
  "gipnoz+misticizm+strelba": "Психокинетик",
  "gipnoz+misticizm+tanec": "Темный иллюзионист",
  "gipnoz+misticizm+volshebstvo": "Астролог",
  "gipnoz+misticizm+voodush": "Эмпат",
  "gipnoz+napadenie+oborona": "Стратег",
  "gipnoz+napadenie+presledovanie": "Ассасин",
  "gipnoz+napadenie+skritnost": "Убийца",
  "gipnoz+napadenie+soprotivlenie": "Дознаватель",
  "gipnoz+napadenie+strelba": "Баллистик",
  "gipnoz+napadenie+tanec": "Бесстрастный скальд",
  "gipnoz+napadenie+volshebstvo": "Пcионик",
  "gipnoz+napadenie+voodush": "Мнемоник",
  "gipnoz+oborona+presledovanie": "Юстициарий",
  "gipnoz+oborona+skritnost": "Лазутчик",
  "gipnoz+oborona+soprotivlenie": "Страж",
  "gipnoz+oborona+strelba": "Часовой",
  "gipnoz+oborona+tanec": "Стойкий иллюзионист",
  "gipnoz+oborona+volshebstvo": "Телепат",
  "gipnoz+oborona+voodush": "Бард",
  "gipnoz+presledovanie+skritnost": "Разведчик",
  "gipnoz+presledovanie+soprotivlenie": "Усмиритель",
  "gipnoz+presledovanie+strelba": "Преследователь",
  "gipnoz+presledovanie+tanec": "Неутомимый иллюзионист",
  "gipnoz+presledovanie+volshebstvo": "Месмер",
  "gipnoz+presledovanie+voodush": "Трубадур",
  "gipnoz+skritnost+soprotivlenie": "Мошенник",
  "gipnoz+skritnost+strelba": "Похититель",
  "gipnoz+skritnost+tanec": "Неуловимый иллюзионист",
  "gipnoz+skritnost+volshebstvo": "Фанатик",
  "gipnoz+skritnost+voodush": "Импровизатор",
  "gipnoz+soprotivlenie+strelba": "Махинатор",
  "gipnoz+soprotivlenie+tanec": "Вещий иллюзионист",
  "gipnoz+soprotivlenie+volshebstvo": "Теолог",
  "gipnoz+soprotivlenie+voodush": "Вестник",
  "gipnoz+strelba+tanec": "Бесстрастный гистрион",
  "gipnoz+strelba+volshebstvo": "Ведун",
  "gipnoz+strelba+voodush": "Безумец",
  "gipnoz+tanec+volshebstvo": "Мудрый иллюзионист",
  "gipnoz+tanec+voodush": "Вдохновенный иллюзионист",
  "gipnoz+volshebstvo+voodush": "Сновидец",
  "gnev+isceleine+kovarstvo": "Гематик",
  "gnev+isceleine+misticizm": "Волхв",
  "gnev+isceleine+napadenie": "Подстрекатель",
  "gnev+isceleine+oborona": "Кондотьер",
  "gnev+isceleine+presledovanie": "Эпигон",
  "gnev+isceleine+skritnost": "Хронист",
  "gnev+isceleine+soprotivlenie": "Понтифик",
  "gnev+isceleine+strelba": "Медик",
  "gnev+isceleine+tanec": "Яростный медиум",
  "gnev+isceleine+volshebstvo": "Прорицатель",
  "gnev+isceleine+voodush": "Скриптор",
  "gnev+kovarstvo+misticizm": "Хунган",
  "gnev+kovarstvo+napadenie": "Мучитель",
  "gnev+kovarstvo+oborona": "Легионер",
  "gnev+kovarstvo+presledovanie": "Истребитель",
  "gnev+kovarstvo+skritnost": "Терзатель",
  "gnev+kovarstvo+soprotivlenie": "Тиран",
  "gnev+kovarstvo+strelba": "Корсар",
  "gnev+kovarstvo+tanec": "Яростный иерофант",
  "gnev+kovarstvo+volshebstvo": "Демиург",
  "gnev+kovarstvo+voodush": "Агитатор",
  "gnev+misticizm+napadenie": "Клеймитель",
  "gnev+misticizm+oborona": "Трикстер",
  "gnev+misticizm+presledovanie": "Мара",
  "gnev+misticizm+skritnost": "Некромант",
  "gnev+misticizm+soprotivlenie": "Архат",
  "gnev+misticizm+strelba": "Радикал",
  "gnev+misticizm+tanec": "Яростный сновидец",
  "gnev+misticizm+volshebstvo": "Визионер",
  "gnev+misticizm+voodush": "Паяц",
  "gnev+napadenie+oborona": "Берсерк",
  "gnev+napadenie+presledovanie": "Ликтор",
  "gnev+napadenie+skritnost": "Истязатель",
  "gnev+napadenie+soprotivlenie": "Провокатор",
  "gnev+napadenie+strelba": "Рейдер",
  "gnev+napadenie+tanec": "Яростный скальд",
  "gnev+napadenie+volshebstvo": "Эокад",
  "gnev+napadenie+voodush": "Архонт",
  "gnev+oborona+presledovanie": "Браконьер",
  "gnev+oborona+skritnost": "Искатель",
  "gnev+oborona+soprotivlenie": "Угнетатель",
  "gnev+oborona+strelba": "Стражник",
  "gnev+oborona+tanec": "Яростный бард",
  "gnev+oborona+volshebstvo": "Протектор",
  "gnev+oborona+voodush": "Прецептор",
  "gnev+presledovanie+skritnost": "Налетчик",
  "gnev+presledovanie+soprotivlenie": "Ординарец",
  "gnev+presledovanie+strelba": "Грабитель",
  "gnev+presledovanie+tanec": "Яростный трубадур",
  "gnev+presledovanie+volshebstvo": "Созидатель",
  "gnev+presledovanie+voodush": "Пацифист",
  "gnev+skritnost+soprotivlenie": "Мизантроп",
  "gnev+skritnost+strelba": "Проклятый",
  "gnev+skritnost+tanec": "Яростный фантом",
  "gnev+skritnost+volshebstvo": "Ведьмак",
  "gnev+skritnost+voodush": "Фокусник",
  "gnev+soprotivlenie+strelba": "Головорез",
  "gnev+soprotivlenie+tanec": "Яростный корибант",
  "gnev+soprotivlenie+volshebstvo": "Дервиш",
  "gnev+soprotivlenie+voodush": "Повстанец",
  "gnev+strelba+tanec": "Яростный гистрион",
  "gnev+strelba+volshebstvo": "Карабинер",
  "gnev+strelba+voodush": "Идеолог",
  "gnev+tanec+volshebstvo": "Яростный жрец",
  "gnev+tanec+voodush": "Яростный пророк",
  "gnev+volshebstvo+voodush": "Экзарх",
  "isceleine+kovarstvo+misticizm": "Отравитель",
  "isceleine+kovarstvo+napadenie": "Схоластик",
  "isceleine+kovarstvo+oborona": "Схимник",
  "isceleine+kovarstvo+presledovanie": "Скиталец",
  "isceleine+kovarstvo+skritnost": "Спиритуалист",
  "isceleine+kovarstvo+soprotivlenie": "Ритуалист",
  "isceleine+kovarstvo+strelba": "Спагирик",
  "isceleine+kovarstvo+tanec": "Великодушный иерофант",
  "isceleine+kovarstvo+volshebstvo": "Тайновидец",
  "isceleine+kovarstvo+voodush": "Утешитель",
  "isceleine+misticizm+napadenie": "Экзорцист",
  "isceleine+misticizm+oborona": "Рыцарь",
  "isceleine+misticizm+presledovanie": "Эзотерик",
  "isceleine+misticizm+skritnost": "Теург",
  "isceleine+misticizm+soprotivlenie": "Еретик",
  "isceleine+misticizm+strelba": "Ортодокс",
  "isceleine+misticizm+tanec": "Великодушный сновидец",
  "isceleine+misticizm+volshebstvo": "Пророк",
  "isceleine+misticizm+voodush": "Медиум",
  "isceleine+napadenie+oborona": "Паладин",
  "isceleine+napadenie+presledovanie": "Догматик",
  "isceleine+napadenie+skritnost": "Инквизитор",
  "isceleine+napadenie+soprotivlenie": "Храмовник",
  "isceleine+napadenie+strelba": "Предсказатель",
  "isceleine+napadenie+tanec": "Великодушный скальд",
  "isceleine+napadenie+volshebstvo": "Чудотворец",
  "isceleine+napadenie+voodush": "Капеллан",
  "isceleine+oborona+presledovanie": "Пастырь",
  "isceleine+oborona+skritnost": "Пилигрим",
  "isceleine+oborona+soprotivlenie": "Целитель",
  "isceleine+oborona+strelba": "Виталист",
  "isceleine+oborona+tanec": "Великодушный бард",
  "isceleine+oborona+volshebstvo": "Мудрец",
  "isceleine+oborona+voodush": "Миротворец",
  "isceleine+presledovanie+skritnost": "Авантюрист",
  "isceleine+presledovanie+soprotivlenie": "Отшельник",
  "isceleine+presledovanie+strelba": "Суйгун",
  "isceleine+presledovanie+tanec": "Великодушный трубадур",
  "isceleine+presledovanie+volshebstvo": "Геомант",
  "isceleine+presledovanie+voodush": "Миссионер",
  "isceleine+skritnost+soprotivlenie": "Стоик",
  "isceleine+skritnost+strelba": "Эсхатолог",
  "isceleine+skritnost+tanec": "Великодушный фантом",
  "isceleine+skritnost+volshebstvo": "Оракул",
  "isceleine+skritnost+voodush": "Паломник",
  "isceleine+soprotivlenie+strelba": "Метафизик",
  "isceleine+soprotivlenie+tanec": "Великодушный корибант",
  "isceleine+soprotivlenie+volshebstvo": "Жрец",
  "isceleine+soprotivlenie+voodush": "Эскулап",
  "isceleine+strelba+tanec": "Великодушный гистрион",
  "isceleine+strelba+volshebstvo": "Мнемист",
  "isceleine+strelba+voodush": "Комедиант",
  "isceleine+tanec+volshebstvo": "Великодушный жрец",
  "isceleine+tanec+voodush": "Великодушный пророк",
  "isceleine+volshebstvo+voodush": "Авгур",
  "kovarstvo+misticizm+napadenie": "Кошмар",
  "kovarstvo+misticizm+oborona": "Аргус",
  "kovarstvo+misticizm+presledovanie": "Оборотень",
  "kovarstvo+misticizm+skritnost": "Тень",
  "kovarstvo+misticizm+soprotivlenie": "Зелот",
  "kovarstvo+misticizm+strelba": "Надсмотрщик",
  "kovarstvo+misticizm+tanec": "Темный иерофант",
  "kovarstvo+misticizm+volshebstvo": "Факир",
  "kovarstvo+misticizm+voodush": "Вольнодумец",
  "kovarstvo+napadenie+oborona": "Единоборец",
  "kovarstvo+napadenie+presledovanie": "Разоритель",
  "kovarstvo+napadenie+skritnost": "Преступник",
  "kovarstvo+napadenie+soprotivlenie": "Изувер",
  "kovarstvo+napadenie+strelba": "Ганфайтер",
  "kovarstvo+napadenie+tanec": "Решительный иерофант",
  "kovarstvo+napadenie+volshebstvo": "Менталист",
  "kovarstvo+napadenie+voodush": "Мятежник",
  "kovarstvo+oborona+presledovanie": "Рудиарий",
  "kovarstvo+oborona+skritnost": "Конвергент",
  "kovarstvo+oborona+soprotivlenie": "Самнит",
  "kovarstvo+oborona+strelba": "Аферист",
  "kovarstvo+oborona+tanec": "Стойкий иерофант",
  "kovarstvo+oborona+volshebstvo": "Телемит",
  "kovarstvo+oborona+voodush": "Трувер",
  "kovarstvo+presledovanie+skritnost": "Гонитель",
  "kovarstvo+presledovanie+soprotivlenie": "Варвар",
  "kovarstvo+presledovanie+strelba": "Соглядатай",
  "kovarstvo+presledovanie+tanec": "Неутомимый иерофант",
  "kovarstvo+presledovanie+volshebstvo": "Уничтожитель",
  "kovarstvo+presledovanie+voodush": "Эмиссар",
  "kovarstvo+skritnost+soprotivlenie": "Изгнанник",
  "kovarstvo+skritnost+strelba": "Шпион",
  "kovarstvo+skritnost+tanec": "Неуловимый иерофант",
  "kovarstvo+skritnost+volshebstvo": "Магик",
  "kovarstvo+skritnost+voodush": "Заговорщик",
  "kovarstvo+soprotivlenie+strelba": "Приватир",
  "kovarstvo+soprotivlenie+tanec": "Вещий иерофант",
  "kovarstvo+soprotivlenie+volshebstvo": "Одержимый",
  "kovarstvo+soprotivlenie+voodush": "Крамольник",
  "kovarstvo+strelba+tanec": "Жестокий гистрион",
  "kovarstvo+strelba+volshebstvo": "Агент",
  "kovarstvo+strelba+voodush": "Буканир",
  "kovarstvo+tanec+volshebstvo": "Мудрый иерофант",
  "kovarstvo+tanec+voodush": "Вдохновенный иерофант",
  "kovarstvo+volshebstvo+voodush": "Ясновидящий",
  "misticizm+napadenie+oborona": "Палач",
  "misticizm+napadenie+presledovanie": "Дуэлянт",
  "misticizm+napadenie+skritnost": "Потрошитель",
  "misticizm+napadenie+soprotivlenie": "Демонолог",
  "misticizm+napadenie+strelba": "Заговариватель",
  "misticizm+napadenie+tanec": "Темный скальд",
  "misticizm+napadenie+volshebstvo": "Оккультист",
  "misticizm+napadenie+voodush": "Скальд",
  "misticizm+oborona+presledovanie": "Ловчий",
  "misticizm+oborona+skritnost": "Мародер",
  "misticizm+oborona+soprotivlenie": "Тактик",
  "misticizm+oborona+strelba": "Шарпшутер",
  "misticizm+oborona+tanec": "Темный бард",
  "misticizm+oborona+volshebstvo": "Каратель",
  "misticizm+oborona+voodush": "Маэстро",
  "misticizm+presledovanie+skritnost": "Вивисектор",
  "misticizm+presledovanie+soprotivlenie": "Загонщик",
  "misticizm+presledovanie+strelba": "Сталкер",
  "misticizm+presledovanie+tanec": "Неутомимый сновидец",
  "misticizm+presledovanie+volshebstvo": "Гаруспик",
  "misticizm+presledovanie+voodush": "Егерь",
  "misticizm+skritnost+soprotivlenie": "Осквернитель",
  "misticizm+skritnost+strelba": "Теософ",
  "misticizm+skritnost+tanec": "Неуловимый сновидец",
  "misticizm+skritnost+volshebstvo": "Колдун",
  "misticizm+skritnost+voodush": "Виртуоз",
  "misticizm+soprotivlenie+strelba": "Деист",
  "misticizm+soprotivlenie+tanec": "Темный корибант",
  "misticizm+soprotivlenie+volshebstvo": "Элементалист",
  "misticizm+soprotivlenie+voodush": "Философ",
  "misticizm+strelba+tanec": "Темный гистрион",
  "misticizm+strelba+volshebstvo": "Помнящий",
  "misticizm+strelba+voodush": "Слагатель",
  "misticizm+tanec+volshebstvo": "Мудрый сновидец",
  "misticizm+tanec+voodush": "Вдохновенный сновидец",
  "misticizm+volshebstvo+voodush": "Шаман",
  "napadenie+oborona+presledovanie": "Узурпатор",
  "napadenie+oborona+skritnost": "Наемник",
  "napadenie+oborona+soprotivlenie": "Гладиатор",
  "napadenie+oborona+strelba": "Берсальер",
  "napadenie+oborona+tanec": "Стойкий скальд",
  "napadenie+oborona+volshebstvo": "Монах",
  "napadenie+oborona+voodush": "Защитник",
  "napadenie+presledovanie+skritnost": "Мститель",
  "napadenie+presledovanie+soprotivlenie": "Завоеватель",
  "napadenie+presledovanie+strelba": "Капер",
  "napadenie+presledovanie+tanec": "Неутомимый скальд",
  "napadenie+presledovanie+volshebstvo": "Разрушитель",
  "napadenie+presledovanie+voodush": "Полководец",
  "napadenie+skritnost+soprotivlenie": "Разбойник",
  "napadenie+skritnost+strelba": "Пират",
  "napadenie+skritnost+tanec": "Неуловимый скальд",
  "napadenie+skritnost+volshebstvo": "Хиромант",
  "napadenie+skritnost+voodush": "Судья",
  "napadenie+soprotivlenie+strelba": "Старатель",
  "napadenie+soprotivlenie+tanec": "Вещий скальд",
  "napadenie+soprotivlenie+volshebstvo": "Вершитель",
  "napadenie+soprotivlenie+voodush": "Глашатай",
  "napadenie+strelba+tanec": "Решительный гистрион",
  "napadenie+strelba+volshebstvo": "Мольфар",
  "napadenie+strelba+voodush": "Эвритмик",
  "napadenie+tanec+volshebstvo": "Мудрый скальд",
  "napadenie+tanec+voodush": "Вдохновенный скальд",
  "napadenie+volshebstvo+voodush": "Магистр",
  "oborona+presledovanie+skritnost": "Охотник",
  "oborona+presledovanie+soprotivlenie": "Застрельщик",
  "oborona+presledovanie+strelba": "Телохранитель",
  "oborona+presledovanie+tanec": "Неутомимый бард",
  "oborona+presledovanie+volshebstvo": "Каббалист",
  "oborona+presledovanie+voodush": "Вождь",
  "oborona+skritnost+soprotivlenie": "Контрабандист",
  "oborona+skritnost+strelba": "Атаман",
  "oborona+skritnost+tanec": "Неуловимый бард",
  "oborona+skritnost+volshebstvo": "Хранитель",
  "oborona+skritnost+voodush": "Дозорный",
  "oborona+soprotivlenie+strelba": "Шериф",
  "oborona+soprotivlenie+tanec": "Вещий бард",
  "oborona+soprotivlenie+volshebstvo": "Госпитальер",
  "oborona+soprotivlenie+voodush": "Менестрель",
  "oborona+strelba+tanec": "Стойкий гистрион",
  "oborona+strelba+volshebstvo": "Аломант",
  "oborona+strelba+voodush": "Гвардеец",
  "oborona+tanec+volshebstvo": "Мудрый бард",
  "oborona+tanec+voodush": "Вдохновенный бард",
  "oborona+volshebstvo+voodush": "Заступник",
  "presledovanie+skritnost+soprotivlenie": "Следопыт",
  "presledovanie+skritnost+strelba": "Траппер",
  "presledovanie+skritnost+tanec": "Неуловимый трубадур",
  "presledovanie+skritnost+volshebstvo": "Фантом",
  "presledovanie+skritnost+voodush": "Сказитель",
  "presledovanie+soprotivlenie+strelba": "Аркебузир",
  "presledovanie+soprotivlenie+tanec": "Неутомимый корибант",
  "presledovanie+soprotivlenie+volshebstvo": "Анахорет",
  "presledovanie+soprotivlenie+voodush": "Странник",
  "presledovanie+strelba+tanec": "Неутомимый гистрион",
  "presledovanie+strelba+volshebstvo": "Сарбаз",
  "presledovanie+strelba+voodush": "Флибустьер",
  "presledovanie+tanec+volshebstvo": "Мудрый трубадур",
  "presledovanie+tanec+voodush": "Вдохновенный трубадур",
  "presledovanie+volshebstvo+voodush": "Друид",
  "skritnost+soprotivlenie+strelba": "Комбинатор",
  "skritnost+soprotivlenie+tanec": "Неуловимый корибант",
  "skritnost+soprotivlenie+volshebstvo": "Шулер",
  "skritnost+soprotivlenie+voodush": "Плут",
  "skritnost+strelba+tanec": "Неуловимый гистрион",
  "skritnost+strelba+volshebstvo": "Мушкетер",
  "skritnost+strelba+voodush": "Вагант",
  "skritnost+tanec+volshebstvo": "Неуловимый жрец",
  "skritnost+tanec+voodush": "Вдохновенный фантом",
  "skritnost+volshebstvo+voodush": "Чародей",
  "soprotivlenie+strelba+tanec": "Вещий гистрион",
  "soprotivlenie+strelba+volshebstvo": "Бунтовщик",
  "soprotivlenie+strelba+voodush": "Лицедей",
  "soprotivlenie+tanec+volshebstvo": "Мудрый корибант",
  "soprotivlenie+tanec+voodush": "Вдохновенный корибант",
  "soprotivlenie+volshebstvo+voodush": "Летописец",
  "strelba+tanec+volshebstvo": "Мудрый гистрион",
  "strelba+tanec+voodush": "Вдохновенный гистрион",
  "strelba+volshebstvo+voodush": "Знаменный",
  "tanec+volshebstvo+voodush": "Вдохновенный жрец",
};

export function getComboKey(ids: (string | null)[]): string | null {
  const filtered = ids.filter((id): id is string => !!id);
  if (filtered.length !== 3) return null;
  if (new Set(filtered).size !== 3) return null;
  return [...filtered].sort().join("+");
}

export function lookupClassName(ids: (string | null)[]): string | null {
  const key = getComboKey(ids);
  if (!key) return null;
  return CLASS_NAME_BY_COMBO[key] ?? null;
}
