// Generated by db/generate-types.mjs from the live schema. Run `pnpm db:types` after migrations.

export type ExpenseRow = {
  id: number;
  date: string;
  amount: number;
  target: string;
  source: string;
  comment: string | null;
};

export type GuildFundsRow = {
  id: number;
  year: number;
  month: number;
  totalIncome: number;
  totalExpenses: number;
  salaryBudget: number;
  inTreasury: number | null;
  advanceSent: number | null;
  treasuryBudget: number | null;
  carryOver: number;
};

export type NewsRow = {
  id: number;
  title: string;
  content: string;
  date: string;
  createdAt: string;
  updatedAt: string;
};

export type SalaryRow = {
  id: number;
  year: number;
  month: number;
  userId: number;
  amount: number;
  bonus: number | null;
  total: number;
  sentAmount: number;
  sent: boolean;
  tenurePercent: number;
  customBonusPercent: number;
  penaltyPercent: number;
  weightPercent: number;
  aglPercent: number;
  primePercent: number;
  totalPercent: number;
};

export type AnniversaryCheersRow = {
  id: number;
  user_id: number;
  years: number;
  cheered_by: number;
  created_at: string;
};

export type AttendanceBonusBossRow = {
  bonus_type_id: number;
  boss_id: number;
};

export type AttendanceBonusSettingsRow = {
  id: number;
  updated_at: string;
  pvp_points_freeshard: number;
  pvp_points_pvp: number;
  pvp_long_points_freeshard: number;
  pvp_long_points_pvp: number;
  proc_points_freeshard: number;
  proc_points_pvp: number;
  double_proc_points_freeshard: number;
  double_proc_points_pvp: number;
};

export type AttendanceBonusTypesRow = {
  id: number;
  label: string;
  value_freeshard: number;
  value_pvp: number;
  sort_order: number;
  created_at: string;
  mode_freeshard: string;
  mode_pvp: string;
};

export type AvatarFrameRow = {
  id: number;
  name: string;
  image_url: string;
  unlock_type: string;
  unlock_value: number;
  unlock_class: string | null;
};

export type BossRow = {
  id: number;
  boss_name: string;
  dkp_points: number;
  category: string | null;
  dkp_points_freeshard: number;
  dkp_points_pvp: number;
};

export type BossKillRaidSuggestionsRow = {
  boss_name: string;
  kill_time: string;
  created_at: string;
  id: number;
  status: string;
};

export type BossMaintenanceWindowsRow = {
  id: string;
  start_at: string;
  end_at: string;
  created_by: number | null;
  created_at: string;
};

export type BossRespawnRow = {
  boss_name: string;
  last_kill: string | null;
  packs_needed: number | null;
  updated_by: number | null;
  updated_at: string | null;
  notify_message_id: string | null;
  missed_message_id: string | null;
};

export type BossRespawnHistoryRow = {
  id: string;
  boss_name: string;
  action: string;
  kill_time: string;
  prev_kill_time: string | null;
  next_respawn: string | null;
  user_id: number | null;
  created_at: string;
  packs_needed: number | null;
};

export type CalculatorBuildRow = {
  id: number;
  author_id: number;
  build: unknown;
  updated_at: string;
};

export type CalculatorShareRow = {
  id: string;
  author_id: number;
  builds: unknown;
  created_at: string;
};

export type EventSettingsRow = {
  id: number;
  title: string | null;
  image_url: string | null;
  ends_at: string | null;
  updated_at: string;
  starts_at: string | null;
  link: string | null;
  promo: string | null;
};

export type GivenawaylootRow = {
  id: number;
  user_id: number;
  name: string;
  date: string | null;
  comment: string | null;
  created_at: string | null;
  status: string | null;
};

export type GuildBuffSettingsRow = {
  id: number;
  levels: unknown;
  updated_at: string;
};

export type GuildPeriodHistoryRow = {
  id: number;
  mode: string;
  server: string;
  faction: string;
  opponent_guild: string | null;
  started_at: string;
  ended_at: string;
  ended_by_user_id: number | null;
  created_at: string;
  opponent_ended_at: string | null;
};

export type GuildStatusSettingsRow = {
  id: number;
  mode: string;
  updated_at: string;
  server: string | null;
  faction: string | null;
  started_at: string | null;
  opponent_guild: string | null;
  opponent_ended_at: string | null;
};

export type GuildWarOpponentsRow = {
  id: number;
  name: string;
  started_at: string;
  period_history_id: number | null;
  created_at: string;
  ended_at: string | null;
};

export type InventoryStockSettingsRow = {
  id: number;
  hidden_labels: string[];
  updated_at: string;
};

export type ItemTypeRow = {
  id: number;
  name: string;
  price: number | null;
  icon_url: string | null;
  grade: number;
  source: string | null;
  show_in_buy: boolean;
  category: string | null;
};

export type KillcountEventsRow = {
  id: number;
  name: string;
  description: string | null;
};

export type KillcountStatsRow = {
  id: number;
  user_id: number | null;
  event_id: number;
  start_honor: number | null;
  end_honor: number | null;
  start_kills: number | null;
  end_kills: number | null;
  created_at: string | null;
  updated_at: string | null;
  recorded_at: string;
  class: string | null;
  comment: string | null;
};

export type LinkTokenRow = {
  id: number;
  token: string;
  userId: number;
  expiresAt: string;
  used: boolean;
};

export type LootRow = {
  id: number;
  status: string | null;
  sold_at: string | null;
  sold_to: string | null;
  comment: string | null;
  created_at: string;
  source: string | null;
  acquired_at: string | null;
  item_type_id: number;
  sold_to_user_id: number | null;
  quantity: number;
  price: number | null;
  group_id: number | null;
  raid_id: number | null;
};

export type LootQueueRow = {
  id: number;
  item_type_id: number;
  user_id: number;
  created_at: string | null;
  status: string | null;
  synth_target: string | null;
  remaining: number | null;
  required: number;
  delivered: number;
  roll: number | null;
  position: number | null;
};

export type LootWishlistRow = {
  id: string;
  user_id: number;
  item_name: string;
  comment: string | null;
  created_at: string;
};

export type MarketplaceItemTypeRow = {
  id: number;
  name: string;
  icon_url: string | null;
  created_at: string;
  grade: number;
};

export type MarketplaceListingsRow = {
  id: number;
  user_id: number;
  item_name: string;
  quantity: number;
  price: number | null;
  description: string | null;
  created_at: string;
  image_url: string | null;
  currency: string;
  listing_type: string;
  catalog_item_id: number | null;
};

export type MiscLootGrantsRow = {
  id: string;
  user_id: number;
  comment: string;
  amount: number | null;
  date: string;
  created_at: string;
};

export type MiscLootTotalsRow = {
  id: number;
  item_name: string;
  month: number;
  year: number;
  amount: number;
  updated_at: string;
};

export type MissingActivityOverridesRow = {
  id: number;
  activity_date: string;
  time: string;
  boss_name: string;
  kind: string;
  created_at: string;
};

export type ProfileCoverRow = {
  id: number;
  image_url: string;
};

export type ProfileItemTypeRow = {
  id: number;
  name: string;
  category: string;
  icon_url: string | null;
  created_at: string;
};

export type PromoCharacterRow = {
  id: number;
  user_id: number;
  name: string;
  server: string | null;
  group_id: number | null;
  position: number;
  created_at: string;
};

export type PromoProgressRow = {
  character_id: number;
  event: string;
  week_start: string;
  quest_id: number;
  day_index: number;
  created_at: string;
};

export type RaidRow = {
  id: number;
  type: string | null;
  start_date: string | null;
  created_at: string;
  dkp_summary: number | null;
  active_user_count: number | null;
  external_key: string | null;
  updated_at: string;
};

export type RaidAttendanceRow = {
  id: number;
  user_id: number;
  raid_id: number;
  created_at: string;
  updated_at: string;
  is_late: boolean;
};

export type RaidBonusRow = {
  raid_id: number;
  bonus_type_id: number;
};

export type RaidBossRow = {
  raid_id: number;
  boss_id: number;
};

export type SalaryEligibilitySettingsRow = {
  id: number;
  prime_enabled: boolean;
  prime_threshold_percent: number;
  points_enabled: boolean;
  points_threshold_percent: number;
  dv_bypass_enabled: boolean;
  gs_enabled: boolean;
  updated_at: string;
};

export type ScreenshotsLinkSettingsRow = {
  id: number;
  url: string;
  month_label: string;
  updated_at: string;
};

export type TasksRow = {
  id: number;
  user_id: number;
  name: string | null;
  completed_at: string | null;
  created_at: string;
};

export type TasksUserRow = {
  tasks_user_id: number;
  user_id: number;
};

export type UserRow = {
  id: number;
  username: string;
  class: string | null;
  secondary_class: string | null;
  class_gear_score: number | null;
  secondary_class_gear_score: number | null;
  vk_name: string | null;
  active: boolean;
  is_eligible_for_salary: boolean;
  joined_at: string | null;
  created_at: string;
  salaryBonus: number | null;
  google_id: string | null;
  vk_id: string | null;
  mail_id: string | null;
  session_token: string | null;
  last_seen_at: string | null;
  avatar_url: string | null;
  inactive_since: string | null;
  probation_bypass: boolean;
  tertiary_class: string | null;
  tertiary_class_gear_score: number | null;
  character_level: number;
  character_portrait_url: string | null;
  probation_salary_granted: boolean;
  character_buffs: unknown;
  cover_url: string | null;
  avatar_frame_id: number | null;
  profile_effect: string | null;
};

export type UserArchetypeRow = {
  user_id: number;
  specialization_1: string | null;
  specialization_2: string | null;
  specialization_3: string | null;
  class_name: string | null;
  updated_at: string;
  role_slot: number;
};

export type UserCharacterBuffsRow = {
  user_id: number;
  role_slot: number;
  buffs: unknown;
  updated_at: string;
};

export type UserEquipmentRow = {
  id: number;
  user_id: number;
  slot: string;
  item_name: string | null;
  grade: number;
  created_at: string;
  enchant: number;
  extra_protection: number;
  engravings: number[];
  rune_id: number;
  costume_synthesis_effects: number[];
  underwear_synthesis_effects: number[];
  cursed_synthesis_effects: number[];
  ephen_synthesis_percent: number;
  ephen_synthesis_primary: string;
  ephen_synthesis_secondary: string;
  ephen_synthesis_tertiary: string[];
  ring_synthesis_effects: number[];
  ephe_seal_level: number;
  synthesis_effects: number[];
  synthesis_percent: number;
  role_slot: number;
};

export type UserInventoryRow = {
  id: number;
  user_id: number;
  type: string | null;
  name: string | null;
  quality: string | null;
  created_at: string;
  quantity: number | null;
  loot_id: number | null;
};

export type UserPenaltyPointsRow = {
  id: number;
  user_id: number;
  amount: number;
  reason: string;
  created_at: string;
};

export type UserSalaryBonusRow = {
  id: number;
  user_id: number;
  amount: number;
  reason: string;
  created_at: string | null;
};

export type UserSealsRow = {
  id: number;
  user_id: number;
  seal_name: string;
  grade: number;
  created_at: string;
  level: number;
};

export type UserSelfEditSettingsRow = {
  id: number;
  nickname_edit_enabled: boolean;
  gs_edit_enabled: boolean;
  inventory_edit_enabled: boolean;
  updated_at: string;
  seals_edit_enabled: boolean;
  archetype_edit_enabled: boolean;
  extra_role_edit_enabled: boolean;
  equipment_edit_enabled: boolean;
  vk_edit_enabled: boolean;
};

export type UserSessionRow = {
  token_hash: string;
  user_id: number;
  created_at: string;
  expires_at: string;
  user_agent: string | null;
};

export type UserSkillBuildRow = {
  user_id: number;
  role_slot: number;
  build: unknown;
  updated_at: string;
};

export type UserTagsRow = {
  id: number;
  user_id: number;
  tag: string;
  created_at: string;
  removed_at: string | null;
};

export type UserUsernameHistoryRow = {
  id: number;
  user_id: number;
  old_username: string;
  new_username: string;
  changed_at: string;
};

export type VkNotificationSettingsRow = {
  id: number;
  enabled_bosses: string[];
  notify_before_minutes: number;
  quiet_hours_enabled: boolean;
  quiet_hours_start: number;
  quiet_hours_end: number;
  updated_at: string;
  notify_minutes_by_event: unknown;
  prime_time: string | null;
  prime_days: number[] | null;
};

export type VkScheduleNotifyLogRow = {
  event_key: string;
  notified_at: string;
};

export type VoucherReportRow = {
  server: string;
  period: string;
  zone: string;
  amount: number;
  user_id: number;
  updated_at: string;
};

export type WeekScheduleEventRow = {
  weekday: string;
  time: string;
  boss_name: string;
  comment: string | null;
  created_at: string | null;
  updated_at: string | null;
  id: number;
};
