import { writeFileSync } from "node:fs";
import postgres from "postgres";

const OUTPUT = "src/shared/lib/dbTypes.ts";

const TYPE_BY_UDT = {
  int2: "number",
  int4: "number",
  float4: "number",
  float8: "number",
  numeric: "number",
  int8: "string",
  text: "string",
  varchar: "string",
  bool: "boolean",
  date: "string",
  timestamp: "string",
  timestamptz: "string",
  jsonb: "unknown",
  json: "unknown",
  _text: "string[]",
  _varchar: "string[]",
  _int4: "number[]",
};

const sql = postgres(process.env.DATABASE_URL, { max: 1 });

const columns = await sql`
  SELECT table_name, column_name, udt_name, is_nullable
  FROM information_schema.columns
  WHERE table_schema = 'public'
  ORDER BY table_name, ordinal_position
`;
await sql.end();

const tables = new Map();
for (const column of columns) {
  if (!tables.has(column.table_name)) tables.set(column.table_name, []);
  tables.get(column.table_name).push(column);
}

const blocks = [...tables].map(([table, tableColumns]) => {
  const fields = tableColumns.map((column) => {
    const type = TYPE_BY_UDT[column.udt_name];
    if (!type)
      throw new Error(
        `Unknown type ${column.udt_name} in ${table}.${column.column_name}`,
      );
    const nullable = column.is_nullable === "YES" ? " | null" : "";
    return `  ${column.column_name}: ${type}${nullable};`;
  });
  return `export type ${rowTypeName(table)} = {\n${fields.join("\n")}\n};`;
});

writeFileSync(
  OUTPUT,
  `// Generated by db/generate-types.mjs from the live schema. Run \`pnpm db:types\` after migrations.\n\n${blocks.join("\n\n")}\n`,
);
console.log(`${tables.size} tables written to ${OUTPUT}`);

function rowTypeName(table) {
  const pascal = table
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return `${pascal}Row`;
}
