export type EquippedBonuses = {
  manaPercent: number;
  defensePercent: number;
  resistPercent: number;
  meleeAttackPercent: number;
  rangedAttackPercent: number;
  spellPowerPercent: number;
  healPowerPercent: number;
  defense: number;
  resist: number;
  str: number;
  int: number;
  dex: number;
  spi: number;
  sta: number;
  health: number;
  mana: number;
  meleeAttack: number;
  rangedAttack: number;
  spellPower: number;
  healPower: number;
  weaponSpellPower: number;
  weaponHealPower: number;
  moveSpeed: number;
  skillSpeed: number;
  proficiency: number;
  tacticalReadiness: number;
  parry: number;
  dodge: number;
  block: number;
  pvpResist: number;
  critDamageResist: number;
  critChanceMelee: number;
  critChanceRanged: number;
  critChanceSpell: number;
  critChanceHeal: number;
  healthRegen: number;
  manaRegen: number;
};

export const EMPTY_BONUSES: EquippedBonuses = {
  manaPercent: 0,
  defensePercent: 0,
  resistPercent: 0,
  meleeAttackPercent: 0,
  rangedAttackPercent: 0,
  spellPowerPercent: 0,
  healPowerPercent: 0,
  defense: 0,
  resist: 0,
  str: 0,
  int: 0,
  dex: 0,
  spi: 0,
  sta: 0,
  health: 0,
  mana: 0,
  meleeAttack: 0,
  rangedAttack: 0,
  spellPower: 0,
  healPower: 0,
  weaponSpellPower: 0,
  weaponHealPower: 0,
  moveSpeed: 0,
  skillSpeed: 0,
  proficiency: 0,
  tacticalReadiness: 0,
  parry: 0,
  dodge: 0,
  block: 0,
  pvpResist: 0,
  critDamageResist: 0,
  critChanceMelee: 0,
  critChanceRanged: 0,
  critChanceSpell: 0,
  critChanceHeal: 0,
  healthRegen: 0,
  manaRegen: 0,
};
