import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const BELT_ITEMS: GearItem[] = [
  { id: 45886, name: "Матерчатый пояс эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("belt", "матерчатый_пояс_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 45893, name: "Кожаный пояс укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("belt", "кожаный_пояс_укротителя_гримуаров"), sealIconUrl: null },
  { id: 45985, name: "Матерчатый пояс смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("belt", "матерчатый_пояс_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 45900, name: "Латный пояс эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("belt", "латный_пояс_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 47049, name: "Кожаный пояс заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("belt", "кожаный_пояс_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47271, name: "Магистерский матерчатый пояс смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("belt", "магистерский_матерчатый_пояс_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 47284, name: "Магистерский матерчатый пояс эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("belt", "магистерский_матерчатый_пояс_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 47291, name: "Магистерский кожаный пояс укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("belt", "магистерский_кожаный_пояс_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47298, name: "Магистерский кожаный пояс заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("belt", "магистерский_кожаный_пояс_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47305, name: "Магистерский латный пояс эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("belt", "магистерский_латный_пояс_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 49588, name: "Матерчатый пояс эфенского жреца", grade: 7, iconUrl: ITEM_ICON("belt", "матерчатый_пояс_эфенского_жреца"), sealIconUrl: null },
  { id: 49595, name: "Кожаный пояс эфенского искателя истины", grade: 7, iconUrl: ITEM_ICON("belt", "кожаный_пояс_эфенского_искателя_истины"), sealIconUrl: null },
  { id: 49602, name: "Латный пояс эфенского стража святилища", grade: 7, iconUrl: ITEM_ICON("belt", "латный_пояс_эфенского_стража_святилища"), sealIconUrl: null },
  { id: 49609, name: "Матерчатый пояс эфенского алтарника", grade: 7, iconUrl: ITEM_ICON("belt", "матерчатый_пояс_эфенского_алтарника"), sealIconUrl: null },
  { id: 49616, name: "Кожаный пояс эфенского хранителя тайн", grade: 7, iconUrl: ITEM_ICON("belt", "кожаный_пояс_эфенского_хранителя_тайн"), sealIconUrl: null },
  { id: 55418, name: "Матерчатый пояс проклятого жреца", grade: 12, iconUrl: ITEM_ICON("belt", "матерчатый_пояс_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55425, name: "Кожаный пояс проклятого искателя истины", grade: 12, iconUrl: ITEM_ICON("belt", "кожаный_пояс_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55432, name: "Латный пояс проклятого стража святилища", grade: 12, iconUrl: ITEM_ICON("belt", "латный_пояс_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55439, name: "Матерчатый пояс проклятого алтарника", grade: 12, iconUrl: ITEM_ICON("belt", "матерчатый_пояс_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55446, name: "Кожаный пояс проклятого хранителя тайн", grade: 12, iconUrl: ITEM_ICON("belt", "кожаный_пояс_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 900011, name: "Матерчатый пояс возрожденного жреца", grade: 12, iconUrl: ITEM_ICON("belt", "матерчатый_пояс_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900012, name: "Кожаный пояс возрожденного искателя истины", grade: 12, iconUrl: ITEM_ICON("belt", "кожаный_пояс_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900013, name: "Латный пояс возрожденного стража святилища", grade: 12, iconUrl: ITEM_ICON("belt", "латный_пояс_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900014, name: "Матерчатый пояс возрожденного алтарника", grade: 12, iconUrl: ITEM_ICON("belt", "матерчатый_пояс_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900015, name: "Кожаный пояс возрожденного хранителя тайн", grade: 12, iconUrl: ITEM_ICON("belt", "кожаный_пояс_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 45358, name: "Рамианский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "рамианский_латный_пояс"), sealIconUrl: null },
  { id: 45671, name: "Искаженный рамианский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "искаженный_рамианский_латный_пояс"), sealIconUrl: null },
  { id: 45864, name: "Проклятый рамианский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "проклятый_рамианский_латный_пояс"), sealIconUrl: null },
  { id: 46874, name: "Изначальный рамианский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "изначальный_рамианский_латный_пояс"), sealIconUrl: null },
  { id: 48398, name: "Обновленный рамианский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "обновленный_рамианский_латный_пояс"), sealIconUrl: null },
  { id: 53058, name: "Совершенный рамианский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "совершенный_рамианский_латный_пояс"), sealIconUrl: null },
  { id: 45351, name: "Рамианский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "рамианский_кожаный_пояс"), sealIconUrl: null },
  { id: 45664, name: "Искаженный рамианский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "искаженный_рамианский_кожаный_пояс"), sealIconUrl: null },
  { id: 45857, name: "Проклятый рамианский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "проклятый_рамианский_кожаный_пояс"), sealIconUrl: null },
  { id: 46867, name: "Изначальный рамианский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "изначальный_рамианский_кожаный_пояс"), sealIconUrl: null },
  { id: 48391, name: "Обновленный рамианский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "обновленный_рамианский_кожаный_пояс"), sealIconUrl: null },
  { id: 53051, name: "Совершенный рамианский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "совершенный_рамианский_кожаный_пояс"), sealIconUrl: null },
  { id: 45344, name: "Рамианский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "рамианский_матерчатый_пояс"), sealIconUrl: null },
  { id: 45657, name: "Искаженный рамианский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "искаженный_рамианский_матерчатый_пояс"), sealIconUrl: null },
  { id: 45850, name: "Проклятый рамианский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "проклятый_рамианский_матерчатый_пояс"), sealIconUrl: null },
  { id: 46860, name: "Изначальный рамианский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "изначальный_рамианский_матерчатый_пояс"), sealIconUrl: null },
  { id: 48384, name: "Обновленный рамианский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "обновленный_рамианский_матерчатый_пояс"), sealIconUrl: null },
  { id: 53044, name: "Совершенный рамианский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "совершенный_рамианский_матерчатый_пояс"), sealIconUrl: null },
  { id: 54959, name: "Эфенский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "эфенский_латный_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55001, name: "Искаженный эфенский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "искаженный_эфенский_латный_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55044, name: "Изначальный эфенский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "изначальный_эфенский_латный_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55086, name: "Обновленный эфенский латный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "обновленный_эфенский_латный_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54966, name: "Эфенский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "эфенский_кожаный_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55008, name: "Искаженный эфенский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "искаженный_эфенский_кожаный_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55051, name: "Изначальный эфенский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "изначальный_эфенский_кожаный_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55093, name: "Обновленный эфенский кожаный пояс", grade: 1, iconUrl: ITEM_ICON("belt", "обновленный_эфенский_кожаный_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54973, name: "Эфенский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "эфенский_матерчатый_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55015, name: "Искаженный эфенский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "искаженный_эфенский_матерчатый_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55058, name: "Изначальный эфенский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "изначальный_эфенский_матерчатый_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55100, name: "Обновленный эфенский матерчатый пояс", grade: 1, iconUrl: ITEM_ICON("belt", "обновленный_эфенский_матерчатый_пояс"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 20914, name: "Иферийский кожаный пояс охотника", grade: 1, iconUrl: ITEM_ICON("belt", "иферийский_кожаный_пояс_охотника"), sealIconUrl: null },
];
