import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const BRACERS_ITEMS: GearItem[] = [
  { id: 45885, name: "Матерчатые наручи эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("bracers", "матерчатые_наручи_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 45892, name: "Кожаные наручи укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("bracers", "кожаные_наручи_укротителя_гримуаров"), sealIconUrl: null },
  { id: 45986, name: "Матерчатые наручи смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("bracers", "матерчатые_наручи_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 45899, name: "Латные наручи эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("bracers", "латные_наручи_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 47048, name: "Кожаные наручи заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("bracers", "кожаные_наручи_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47272, name: "Магистерские матерчатые наручи смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("bracers", "магистерские_матерчатые_наручи_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 47283, name: "Магистерские матерчатые наручи эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("bracers", "магистерские_матерчатые_наручи_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 47290, name: "Магистерские кожаные наручи укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("bracers", "магистерские_кожаные_наручи_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47297, name: "Магистерские кожаные наручи заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("bracers", "магистерские_кожаные_наручи_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47304, name: "Магистерские латные наручи эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("bracers", "магистерские_латные_наручи_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 49587, name: "Матерчатые наручи эфенского жреца", grade: 7, iconUrl: ITEM_ICON("bracers", "матерчатые_наручи_эфенского_жреца"), sealIconUrl: null },
  { id: 49594, name: "Кожаные наручи эфенского искателя истины", grade: 7, iconUrl: ITEM_ICON("bracers", "кожаные_наручи_эфенского_искателя_истины"), sealIconUrl: null },
  { id: 49601, name: "Латные наручи эфенского стража святилища", grade: 7, iconUrl: ITEM_ICON("bracers", "латные_наручи_эфенского_стража_святилища"), sealIconUrl: null },
  { id: 49608, name: "Матерчатые наручи эфенского алтарника", grade: 7, iconUrl: ITEM_ICON("bracers", "матерчатые_наручи_эфенского_алтарника"), sealIconUrl: null },
  { id: 49615, name: "Кожаные наручи эфенского хранителя тайн", grade: 7, iconUrl: ITEM_ICON("bracers", "кожаные_наручи_эфенского_хранителя_тайн"), sealIconUrl: null },
  { id: 55417, name: "Матерчатые наручи проклятого жреца", grade: 12, iconUrl: ITEM_ICON("bracers", "матерчатые_наручи_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55424, name: "Кожаные наручи проклятого искателя истины", grade: 12, iconUrl: ITEM_ICON("bracers", "кожаные_наручи_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55431, name: "Латные наручи проклятого стража святилища", grade: 12, iconUrl: ITEM_ICON("bracers", "латные_наручи_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55438, name: "Матерчатые наручи проклятого алтарника", grade: 12, iconUrl: ITEM_ICON("bracers", "матерчатые_наручи_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55445, name: "Кожаные наручи проклятого хранителя тайн", grade: 12, iconUrl: ITEM_ICON("bracers", "кожаные_наручи_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 900016, name: "Матерчатые наручи возрожденного жреца", grade: 12, iconUrl: ITEM_ICON("bracers", "матерчатые_наручи_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900017, name: "Кожаные наручи возрожденного искателя истины", grade: 12, iconUrl: ITEM_ICON("bracers", "кожаные_наручи_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900018, name: "Латные наручи возрожденного стража святилища", grade: 12, iconUrl: ITEM_ICON("bracers", "латные_наручи_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900019, name: "Матерчатые наручи возрожденного алтарника", grade: 12, iconUrl: ITEM_ICON("bracers", "матерчатые_наручи_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900020, name: "Кожаные наручи возрожденного хранителя тайн", grade: 12, iconUrl: ITEM_ICON("bracers", "кожаные_наручи_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 45357, name: "Рамианские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "рамианские_латные_наручи"), sealIconUrl: null },
  { id: 45670, name: "Искаженные рамианские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "искаженные_рамианские_латные_наручи"), sealIconUrl: null },
  { id: 45863, name: "Проклятые рамианские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "проклятые_рамианские_латные_наручи"), sealIconUrl: null },
  { id: 46873, name: "Изначальные рамианские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "изначальные_рамианские_латные_наручи"), sealIconUrl: null },
  { id: 48397, name: "Обновленные рамианские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "обновленные_рамианские_латные_наручи"), sealIconUrl: null },
  { id: 53057, name: "Совершенные рамианские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "совершенные_рамианские_латные_наручи"), sealIconUrl: null },
  { id: 45350, name: "Рамианские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "рамианские_кожаные_наручи"), sealIconUrl: null },
  { id: 45663, name: "Искаженные рамианские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "искаженные_рамианские_кожаные_наручи"), sealIconUrl: null },
  { id: 45856, name: "Проклятые рамианские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "проклятые_рамианские_кожаные_наручи"), sealIconUrl: null },
  { id: 46866, name: "Изначальные рамианские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "изначальные_рамианские_кожаные_наручи"), sealIconUrl: null },
  { id: 48390, name: "Обновленные рамианские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "обновленные_рамианские_кожаные_наручи"), sealIconUrl: null },
  { id: 53050, name: "Совершенные рамианские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "совершенные_рамианские_кожаные_наручи"), sealIconUrl: null },
  { id: 45343, name: "Рамианские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "рамианские_матерчатые_наручи"), sealIconUrl: null },
  { id: 45656, name: "Искаженные рамианские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "искаженные_рамианские_матерчатые_наручи"), sealIconUrl: null },
  { id: 45849, name: "Проклятые рамианские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "проклятые_рамианские_матерчатые_наручи"), sealIconUrl: null },
  { id: 46859, name: "Изначальные рамианские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "изначальные_рамианские_матерчатые_наручи"), sealIconUrl: null },
  { id: 48383, name: "Обновленные рамианские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "обновленные_рамианские_матерчатые_наручи"), sealIconUrl: null },
  { id: 53043, name: "Совершенные рамианские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "совершенные_рамианские_матерчатые_наручи"), sealIconUrl: null },
  { id: 54958, name: "Эфенские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "эфенские_латные_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55000, name: "Искаженные эфенские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "искаженные_эфенские_латные_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55043, name: "Изначальные эфенские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "изначальные_эфенские_латные_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55085, name: "Обновленные эфенские латные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "обновленные_эфенские_латные_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54965, name: "Эфенские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "эфенские_кожаные_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55007, name: "Искаженные эфенские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "искаженные_эфенские_кожаные_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55050, name: "Изначальные эфенские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "изначальные_эфенские_кожаные_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55092, name: "Обновленные эфенские кожаные наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "обновленные_эфенские_кожаные_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54972, name: "Эфенские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "эфенские_матерчатые_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55014, name: "Искаженные эфенские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "искаженные_эфенские_матерчатые_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55057, name: "Изначальные эфенские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "изначальные_эфенские_матерчатые_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55099, name: "Обновленные эфенские матерчатые наручи", grade: 1, iconUrl: ITEM_ICON("bracers", "обновленные_эфенские_матерчатые_наручи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 20887, name: "Иферийские кожаные наручи охотника", grade: 1, iconUrl: ITEM_ICON("bracers", "иферийские_кожаные_наручи_охотника"), sealIconUrl: null },
];
