import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const CHEST_ITEMS: GearItem[] = [
  { id: 45881, name: "Матерчатый камзол эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("chest", "матерчатый_камзол_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 45888, name: "Кожаная куртка заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("chest", "кожаная_куртка_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 45990, name: "Матерчатый камзол смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("chest", "матерчатый_камзол_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 45895, name: "Латный нагрудник эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("chest", "латный_нагрудник_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 47044, name: "Кожаная куртка укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("chest", "кожаная_куртка_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47276, name: "Магистерский матерчатый камзол смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("chest", "магистерский_матерчатый_камзол_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 47279, name: "Магистерский матерчатый камзол эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("chest", "магистерский_матерчатый_камзол_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 47286, name: "Магистерская кожаная куртка укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("chest", "магистерская_кожаная_куртка_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47293, name: "Магистерская кожаная куртка заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("chest", "магистерская_кожаная_куртка_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47300, name: "Магистерский латный нагрудник эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("chest", "магистерский_латный_нагрудник_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 49583, name: "Одеяние эфенского жреца", grade: 7, iconUrl: ITEM_ICON("chest", "одеяние_эфенского_жреца"), sealIconUrl: null },
  { id: 49590, name: "Кожаный нагрудник эфенского искателя истины", grade: 7, iconUrl: ITEM_ICON("chest", "кожаный_нагрудник_эфенского_искателя_истины"), sealIconUrl: null },
  { id: 49597, name: "Латный нагрудник эфенского стража святилища", grade: 7, iconUrl: ITEM_ICON("chest", "латный_нагрудник_эфенского_стража_святилища"), sealIconUrl: null },
  { id: 49604, name: "Одеяние эфенского алтарника", grade: 7, iconUrl: ITEM_ICON("chest", "одеяние_эфенского_алтарника"), sealIconUrl: null },
  { id: 49611, name: "Кожаный нагрудник эфенского хранителя тайн", grade: 7, iconUrl: ITEM_ICON("chest", "кожаный_нагрудник_эфенского_хранителя_тайн"), sealIconUrl: null },
  { id: 55413, name: "Одеяние проклятого жреца", grade: 12, iconUrl: ITEM_ICON("chest", "одеяние_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55420, name: "Кожаный нагрудник проклятого искателя истины", grade: 12, iconUrl: ITEM_ICON("chest", "кожаный_нагрудник_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55427, name: "Латный нагрудник проклятого стража святилища", grade: 12, iconUrl: ITEM_ICON("chest", "латный_нагрудник_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55434, name: "Одеяние проклятого алтарника", grade: 12, iconUrl: ITEM_ICON("chest", "одеяние_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55441, name: "Кожаный нагрудник проклятого хранителя тайн", grade: 12, iconUrl: ITEM_ICON("chest", "кожаный_нагрудник_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 900006, name: "Одеяние возрожденного жреца", grade: 12, iconUrl: ITEM_ICON("chest", "одеяние_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900007, name: "Кожаный нагрудник возрожденного искателя истины", grade: 12, iconUrl: ITEM_ICON("chest", "кожаный_нагрудник_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900008, name: "Латный нагрудник возрожденного стража святилища", grade: 12, iconUrl: ITEM_ICON("chest", "латный_нагрудник_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900009, name: "Одеяние возрожденного алтарника", grade: 12, iconUrl: ITEM_ICON("chest", "одеяние_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900010, name: "Кожаный нагрудник возрожденного хранителя тайн", grade: 12, iconUrl: ITEM_ICON("chest", "кожаный_нагрудник_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 45353, name: "Рамианский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "рамианский_латный_нагрудник"), sealIconUrl: null },
  { id: 45666, name: "Искаженный рамианский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "искаженный_рамианский_латный_нагрудник"), sealIconUrl: null },
  { id: 45859, name: "Проклятый рамианский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "проклятый_рамианский_латный_нагрудник"), sealIconUrl: null },
  { id: 46869, name: "Изначальный рамианский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "изначальный_рамианский_латный_нагрудник"), sealIconUrl: null },
  { id: 48393, name: "Обновленный рамианский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "обновленный_рамианский_латный_нагрудник"), sealIconUrl: null },
  { id: 53053, name: "Совершенный рамианский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "совершенный_рамианский_латный_нагрудник"), sealIconUrl: null },
  { id: 45346, name: "Рамианская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "рамианская_кожаная_куртка"), sealIconUrl: null },
  { id: 45659, name: "Искаженная рамианская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "искаженная_рамианская_кожаная_куртка"), sealIconUrl: null },
  { id: 45852, name: "Проклятая рамианская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "проклятая_рамианская_кожаная_куртка"), sealIconUrl: null },
  { id: 46862, name: "Изначальная рамианская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "изначальная_рамианская_кожаная_куртка"), sealIconUrl: null },
  { id: 48386, name: "Обновленная рамианская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "обновленная_рамианская_кожаная_куртка"), sealIconUrl: null },
  { id: 53046, name: "Совершенная рамианская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "совершенная_рамианская_кожаная_куртка"), sealIconUrl: null },
  { id: 45339, name: "Рамианский матерчатый камзол", grade: 1, iconUrl: ITEM_ICON("chest", "рамианский_матерчатый_камзол"), sealIconUrl: null },
  { id: 45652, name: "Искаженный рамианский матерчатый камзол", grade: 1, iconUrl: ITEM_ICON("chest", "искаженный_рамианский_матерчатый_камзол"), sealIconUrl: null },
  { id: 45845, name: "Проклятый рамианский матерчатый камзол", grade: 1, iconUrl: ITEM_ICON("chest", "проклятый_рамианский_матерчатый_камзол"), sealIconUrl: null },
  { id: 46855, name: "Изначальный рамианский камзол", grade: 1, iconUrl: ITEM_ICON("chest", "изначальный_рамианский_камзол"), sealIconUrl: null },
  { id: 48379, name: "Обновленный рамианский камзол", grade: 1, iconUrl: ITEM_ICON("chest", "обновленный_рамианский_камзол"), sealIconUrl: null },
  { id: 53039, name: "Совершенный рамианский камзол", grade: 1, iconUrl: ITEM_ICON("chest", "совершенный_рамианский_камзол"), sealIconUrl: null },
  { id: 54954, name: "Эфенский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "эфенский_латный_нагрудник"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 54996, name: "Искаженный эфенский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "искаженный_эфенский_латный_нагрудник"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55039, name: "Изначальный эфенский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "изначальный_эфенский_латный_нагрудник"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55081, name: "Обновленный эфенский латный нагрудник", grade: 1, iconUrl: ITEM_ICON("chest", "обновленный_эфенский_латный_нагрудник"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54961, name: "Эфенская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "эфенская_кожаная_куртка"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55003, name: "Искаженная эфенская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "искаженная_эфенская_кожаная_куртка"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55046, name: "Изначальная эфенская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "изначальная_эфенская_кожаная_куртка"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55088, name: "Обновленная эфенская кожаная куртка", grade: 1, iconUrl: ITEM_ICON("chest", "обновленная_эфенская_кожаная_куртка"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54968, name: "Эфенская матерчатая мантия", grade: 1, iconUrl: ITEM_ICON("chest", "эфенская_матерчатая_мантия"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55010, name: "Искаженная эфенская матерчатая мантия", grade: 1, iconUrl: ITEM_ICON("chest", "искаженная_эфенская_матерчатая_мантия"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55053, name: "Изначальная эфенская матерчатая мантия", grade: 1, iconUrl: ITEM_ICON("chest", "изначальная_эфенская_матерчатая_мантия"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55095, name: "Обновленная эфенская матерчатая мантия", grade: 1, iconUrl: ITEM_ICON("chest", "обновленная_эфенская_матерчатая_мантия"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 48746, name: "Доспех любимца Изы", grade: 1, iconUrl: ITEM_ICON("chest", "доспех_любимца_изы"), sealIconUrl: null },
  { id: 43664, name: "Мантия иферийского советника", grade: 1, iconUrl: ITEM_ICON("chest", "мантия_иферийского_советника"), sealIconUrl: null },
  { id: 48412, name: "Бригантина властелина морей", grade: 1, iconUrl: ITEM_ICON("chest", "бригантина_властелина_морей"), sealIconUrl: SEAL_ICON("top_leviathan") },
  { id: 49377, name: "Доспех избранника Изы", grade: 1, iconUrl: ITEM_ICON("chest", "доспех_избранника_изы"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49382, name: "Мантия иферийского визиря", grade: 1, iconUrl: ITEM_ICON("chest", "мантия_иферийского_визиря"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49372, name: "Бригантина владыки морей", grade: 1, iconUrl: ITEM_ICON("chest", "бригантина_владыки_морей"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 20779, name: "Иферийская кожаная куртка охотника", grade: 1, iconUrl: ITEM_ICON("chest", "иферийская_кожаная_куртка_охотника"), sealIconUrl: null },
];
