import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const FEET_ITEMS: GearItem[] = [
  { id: 45884, name: "Матерчатые сапоги эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("feet", "матерчатые_сапоги_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 45891, name: "Кожаные сапоги укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("feet", "кожаные_сапоги_укротителя_гримуаров"), sealIconUrl: null },
  { id: 45987, name: "Матерчатые сапоги смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("feet", "матерчатые_сапоги_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 45898, name: "Латные сапоги эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("feet", "латные_сапоги_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 47047, name: "Кожаные сапоги заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("feet", "кожаные_сапоги_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47273, name: "Магистерские матерчатые сапоги смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("feet", "магистерские_матерчатые_сапоги_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 47282, name: "Магистерские матерчатые сапоги эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("feet", "магистерские_матерчатые_сапоги_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 47289, name: "Магистерские кожаные сапоги укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("feet", "магистерские_кожаные_сапоги_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47296, name: "Магистерские кожаные сапоги заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("feet", "магистерские_кожаные_сапоги_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47303, name: "Магистерские латные сапоги эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("feet", "магистерские_латные_сапоги_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 49586, name: "Матерчатые сапоги эфенского жреца", grade: 7, iconUrl: ITEM_ICON("feet", "матерчатые_сапоги_эфенского_жреца"), sealIconUrl: null },
  { id: 49593, name: "Кожаные сапоги эфенского искателя истины", grade: 7, iconUrl: ITEM_ICON("feet", "кожаные_сапоги_эфенского_искателя_истины"), sealIconUrl: null },
  { id: 49600, name: "Латные сапоги эфенского стража святилища", grade: 7, iconUrl: ITEM_ICON("feet", "латные_сапоги_эфенского_стража_святилища"), sealIconUrl: null },
  { id: 49607, name: "Матерчатые сапоги эфенского алтарника", grade: 7, iconUrl: ITEM_ICON("feet", "матерчатые_сапоги_эфенского_алтарника"), sealIconUrl: null },
  { id: 49614, name: "Кожаные сапоги эфенского хранителя тайн", grade: 7, iconUrl: ITEM_ICON("feet", "кожаные_сапоги_эфенского_хранителя_тайн"), sealIconUrl: null },
  { id: 55416, name: "Матерчатые сапоги проклятого жреца", grade: 12, iconUrl: ITEM_ICON("feet", "матерчатые_сапоги_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55423, name: "Кожаные сапоги проклятого искателя истины", grade: 12, iconUrl: ITEM_ICON("feet", "кожаные_сапоги_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55430, name: "Латные сапоги проклятого стража святилища", grade: 12, iconUrl: ITEM_ICON("feet", "латные_сапоги_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55437, name: "Матерчатые сапоги проклятого алтарника", grade: 12, iconUrl: ITEM_ICON("feet", "матерчатые_сапоги_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55444, name: "Кожаные сапоги проклятого хранителя тайн", grade: 12, iconUrl: ITEM_ICON("feet", "кожаные_сапоги_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 900031, name: "Матерчатые сапоги возрожденного жреца", grade: 12, iconUrl: ITEM_ICON("feet", "матерчатые_сапоги_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900032, name: "Кожаные сапоги возрожденного искателя истины", grade: 12, iconUrl: ITEM_ICON("feet", "кожаные_сапоги_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900033, name: "Латные сапоги возрожденного стража святилища", grade: 12, iconUrl: ITEM_ICON("feet", "латные_сапоги_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900034, name: "Матерчатые сапоги возрожденного алтарника", grade: 12, iconUrl: ITEM_ICON("feet", "матерчатые_сапоги_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900035, name: "Кожаные сапоги возрожденного хранителя тайн", grade: 12, iconUrl: ITEM_ICON("feet", "кожаные_сапоги_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 45356, name: "Рамианские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "рамианские_латные_сапоги"), sealIconUrl: null },
  { id: 45669, name: "Искаженные рамианские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "искаженные_рамианские_латные_сапоги"), sealIconUrl: null },
  { id: 45862, name: "Проклятые рамианские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "проклятые_рамианские_латные_сапоги"), sealIconUrl: null },
  { id: 46872, name: "Изначальные рамианские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "изначальные_рамианские_латные_сапоги"), sealIconUrl: null },
  { id: 48396, name: "Обновленные рамианские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "обновленные_рамианские_латные_сапоги"), sealIconUrl: null },
  { id: 53056, name: "Совершенные рамианские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "совершенные_рамианские_латные_сапоги"), sealIconUrl: null },
  { id: 45349, name: "Рамианские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "рамианские_кожаные_сапоги"), sealIconUrl: null },
  { id: 45662, name: "Искаженные рамианские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "искаженные_рамианские_кожаные_сапоги"), sealIconUrl: null },
  { id: 45855, name: "Проклятые рамианские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "проклятые_рамианские_кожаные_сапоги"), sealIconUrl: null },
  { id: 46865, name: "Изначальные рамианские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "изначальные_рамианские_кожаные_сапоги"), sealIconUrl: null },
  { id: 48389, name: "Обновленные рамианские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "обновленные_рамианские_кожаные_сапоги"), sealIconUrl: null },
  { id: 53049, name: "Совершенные рамианские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "совершенные_рамианские_кожаные_сапоги"), sealIconUrl: null },
  { id: 45342, name: "Рамианские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "рамианские_матерчатые_сапоги"), sealIconUrl: null },
  { id: 45655, name: "Искаженные рамианские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "искаженные_рамианские_матерчатые_сапоги"), sealIconUrl: null },
  { id: 45848, name: "Проклятые рамианские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "проклятые_рамианские_матерчатые_сапоги"), sealIconUrl: null },
  { id: 46858, name: "Изначальные рамианские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "изначальные_рамианские_матерчатые_сапоги"), sealIconUrl: null },
  { id: 48382, name: "Обновленные рамианские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "обновленные_рамианские_матерчатые_сапоги"), sealIconUrl: null },
  { id: 53042, name: "Совершенные рамианские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "совершенные_рамианские_матерчатые_сапоги"), sealIconUrl: null },
  { id: 54957, name: "Эфенские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "эфенские_латные_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 54999, name: "Искаженные эфенские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "искаженные_эфенские_латные_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55042, name: "Изначальные эфенские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "изначальные_эфенские_латные_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55084, name: "Обновленные эфенские латные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "обновленные_эфенские_латные_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54964, name: "Эфенские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "эфенские_кожаные_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55006, name: "Искаженные эфенские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "искаженные_эфенские_кожаные_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55049, name: "Изначальные эфенские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "изначальные_эфенские_кожаные_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55091, name: "Обновленные эфенские кожаные сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "обновленные_эфенские_кожаные_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54971, name: "Эфенские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "эфенские_матерчатые_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55013, name: "Искаженные эфенские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "искаженные_эфенские_матерчатые_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55056, name: "Изначальные эфенские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "изначальные_эфенские_матерчатые_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55098, name: "Обновленные эфенские матерчатые сапоги", grade: 1, iconUrl: ITEM_ICON("feet", "обновленные_эфенские_матерчатые_сапоги"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 48749, name: "Сапоги любимца Изы", grade: 1, iconUrl: ITEM_ICON("feet", "сапоги_любимца_изы"), sealIconUrl: null },
  { id: 43669, name: "Сапоги иферийского советника", grade: 1, iconUrl: ITEM_ICON("feet", "сапоги_иферийского_советника"), sealIconUrl: null },
  { id: 48415, name: "Сапоги властелина морей", grade: 1, iconUrl: ITEM_ICON("feet", "сапоги_властелина_морей"), sealIconUrl: SEAL_ICON("top_leviathan") },
  { id: 49380, name: "Сапоги избранника Изы", grade: 1, iconUrl: ITEM_ICON("feet", "сапоги_избранника_изы"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49386, name: "Сапоги иферийского визиря", grade: 1, iconUrl: ITEM_ICON("feet", "сапоги_иферийского_визиря"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49375, name: "Сапоги владыки морей", grade: 1, iconUrl: ITEM_ICON("feet", "сапоги_владыки_морей"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 19401, name: "Ласты ныряльщика", grade: 1, iconUrl: ITEM_ICON("feet", "ласты_ныряльщика"), sealIconUrl: null },
  { id: 27784, name: "Тяжелые ласты", grade: 1, iconUrl: ITEM_ICON("feet", "тяжелые_ласты"), sealIconUrl: null },
  { id: 20860, name: "Иферийские кожаные сапоги охотника", grade: 1, iconUrl: ITEM_ICON("feet", "иферийские_кожаные_сапоги_охотника"), sealIconUrl: null },
];
