import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const HANDS_ITEMS: GearItem[] = [
  { id: 45883, name: "Матерчатые перчатки эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("hands", "матерчатые_перчатки_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 45890, name: "Кожаные перчатки заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("hands", "кожаные_перчатки_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 45988, name: "Матерчатые перчатки смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("hands", "матерчатые_перчатки_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 45897, name: "Латные перчатки эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("hands", "латные_перчатки_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 47046, name: "Кожаные перчатки укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("hands", "кожаные_перчатки_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47274, name: "Магистерские матерчатые перчатки смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("hands", "магистерские_матерчатые_перчатки_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 47281, name: "Магистерские матерчатые перчатки эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("hands", "магистерские_матерчатые_перчатки_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 47288, name: "Магистерские кожаные перчатки укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("hands", "магистерские_кожаные_перчатки_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47295, name: "Магистерские кожаные перчатки заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("hands", "магистерские_кожаные_перчатки_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47302, name: "Магистерские латные перчатки эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("hands", "магистерские_латные_перчатки_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 49585, name: "Матерчатые перчатки эфенского жреца", grade: 7, iconUrl: ITEM_ICON("hands", "матерчатые_перчатки_эфенского_жреца"), sealIconUrl: null },
  { id: 49592, name: "Кожаные перчатки эфенского искателя истины", grade: 7, iconUrl: ITEM_ICON("hands", "кожаные_перчатки_эфенского_искателя_истины"), sealIconUrl: null },
  { id: 49599, name: "Латные перчатки эфенского стража святилища", grade: 7, iconUrl: ITEM_ICON("hands", "латные_перчатки_эфенского_стража_святилища"), sealIconUrl: null },
  { id: 49606, name: "Матерчатые перчатки эфенского алтарника", grade: 7, iconUrl: ITEM_ICON("hands", "матерчатые_перчатки_эфенского_алтарника"), sealIconUrl: null },
  { id: 49613, name: "Кожаные перчатки эфенского хранителя тайн", grade: 7, iconUrl: ITEM_ICON("hands", "кожаные_перчатки_эфенского_хранителя_тайн"), sealIconUrl: null },
  { id: 55415, name: "Матерчатые перчатки проклятого жреца", grade: 12, iconUrl: ITEM_ICON("hands", "матерчатые_перчатки_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55422, name: "Кожаные перчатки проклятого искателя истины", grade: 12, iconUrl: ITEM_ICON("hands", "кожаные_перчатки_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55429, name: "Латные перчатки проклятого стража святилища", grade: 12, iconUrl: ITEM_ICON("hands", "латные_перчатки_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55436, name: "Матерчатые перчатки проклятого алтарника", grade: 12, iconUrl: ITEM_ICON("hands", "матерчатые_перчатки_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55443, name: "Кожаные перчатки проклятого хранителя тайн", grade: 12, iconUrl: ITEM_ICON("hands", "кожаные_перчатки_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 900021, name: "Матерчатые перчатки возрожденного жреца", grade: 12, iconUrl: ITEM_ICON("hands", "матерчатые_перчатки_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900022, name: "Кожаные перчатки возрожденного искателя истины", grade: 12, iconUrl: ITEM_ICON("hands", "кожаные_перчатки_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900023, name: "Латные перчатки возрожденного стража святилища", grade: 12, iconUrl: ITEM_ICON("hands", "латные_перчатки_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900024, name: "Матерчатые перчатки возрожденного алтарника", grade: 12, iconUrl: ITEM_ICON("hands", "матерчатые_перчатки_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900025, name: "Кожаные перчатки возрожденного хранителя тайн", grade: 12, iconUrl: ITEM_ICON("hands", "кожаные_перчатки_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 45355, name: "Рамианские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "рамианские_латные_перчатки"), sealIconUrl: null },
  { id: 45668, name: "Искаженные рамианские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "искаженные_рамианские_латные_перчатки"), sealIconUrl: null },
  { id: 45861, name: "Проклятые рамианские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "проклятые_рамианские_латные_перчатки"), sealIconUrl: null },
  { id: 46871, name: "Изначальные рамианские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "изначальные_рамианские_латные_перчатки"), sealIconUrl: null },
  { id: 48395, name: "Обновленные рамианские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "обновленные_рамианские_латные_перчатки"), sealIconUrl: null },
  { id: 53055, name: "Совершенные рамианские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "совершенные_рамианские_латные_перчатки"), sealIconUrl: null },
  { id: 45348, name: "Рамианские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "рамианские_кожаные_перчатки"), sealIconUrl: null },
  { id: 45661, name: "Искаженные рамианские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "искаженные_рамианские_кожаные_перчатки"), sealIconUrl: null },
  { id: 45854, name: "Проклятые рамианские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "проклятые_рамианские_кожаные_перчатки"), sealIconUrl: null },
  { id: 46864, name: "Изначальные рамианские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "изначальные_рамианские_кожаные_перчатки"), sealIconUrl: null },
  { id: 48388, name: "Обновленные рамианские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "обновленные_рамианские_кожаные_перчатки"), sealIconUrl: null },
  { id: 53048, name: "Совершенные рамианские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "совершенные_рамианские_кожаные_перчатки"), sealIconUrl: null },
  { id: 45341, name: "Рамианские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "рамианские_матерчатые_перчатки"), sealIconUrl: null },
  { id: 45654, name: "Искаженные рамианские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "искаженные_рамианские_матерчатые_перчатки"), sealIconUrl: null },
  { id: 45847, name: "Проклятые рамианские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "проклятые_рамианские_матерчатые_перчатки"), sealIconUrl: null },
  { id: 46857, name: "Изначальные рамианские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "изначальные_рамианские_матерчатые_перчатки"), sealIconUrl: null },
  { id: 48381, name: "Обновленные рамианские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "обновленные_рамианские_матерчатые_перчатки"), sealIconUrl: null },
  { id: 53041, name: "Совершенные рамианские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "совершенные_рамианские_матерчатые_перчатки"), sealIconUrl: null },
  { id: 54956, name: "Эфенские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "эфенские_латные_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 54998, name: "Искаженные эфенские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "искаженные_эфенские_латные_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55041, name: "Изначальные эфенские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "изначальные_эфенские_латные_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55083, name: "Обновленные эфенские латные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "обновленные_эфенские_латные_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54963, name: "Эфенские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "эфенские_кожаные_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55005, name: "Искаженные эфенские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "искаженные_эфенские_кожаные_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55048, name: "Изначальные эфенские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "изначальные_эфенские_кожаные_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55090, name: "Обновленные эфенские кожаные перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "обновленные_эфенские_кожаные_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54970, name: "Эфенские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "эфенские_матерчатые_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55012, name: "Искаженные эфенские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "искаженные_эфенские_матерчатые_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55055, name: "Изначальные эфенские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "изначальные_эфенские_матерчатые_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55097, name: "Обновленные эфенские матерчатые перчатки", grade: 1, iconUrl: ITEM_ICON("hands", "обновленные_эфенские_матерчатые_перчатки"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 48748, name: "Перчатки любимца Изы", grade: 1, iconUrl: ITEM_ICON("hands", "перчатки_любимца_изы"), sealIconUrl: null },
  { id: 43666, name: "Перчатки иферийского советника", grade: 1, iconUrl: ITEM_ICON("hands", "перчатки_иферийского_советника"), sealIconUrl: null },
  { id: 48414, name: "Перчатки властелина морей", grade: 1, iconUrl: ITEM_ICON("hands", "перчатки_властелина_морей"), sealIconUrl: SEAL_ICON("top_leviathan") },
  { id: 49379, name: "Перчатки избранника Изы", grade: 1, iconUrl: ITEM_ICON("hands", "перчатки_избранника_изы"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49384, name: "Перчатки иферийского визиря", grade: 1, iconUrl: ITEM_ICON("hands", "перчатки_иферийского_визиря"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49374, name: "Перчатки владыки морей", grade: 1, iconUrl: ITEM_ICON("hands", "перчатки_владыки_морей"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 20833, name: "Иферийские кожаные перчатки охотника", grade: 1, iconUrl: ITEM_ICON("hands", "иферийские_кожаные_перчатки_охотника"), sealIconUrl: null },
];
