import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const HEAD_ITEMS: GearItem[] = [
  { id: 45880, name: "Диадема эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("head", "диадема_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 45887, name: "Фибула заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("head", "фибула_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 45991, name: "Диадема смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("head", "диадема_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 45894, name: "Латный шлем эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("head", "латный_шлем_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 47043, name: "Фибула укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("head", "фибула_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47277, name: "Магистерская диадема смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("head", "магистерская_диадема_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 47278, name: "Магистерская диадема эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("head", "магистерская_диадема_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 47285, name: "Магистерская фибула укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("head", "магистерская_фибула_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47292, name: "Магистерская фибула заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("head", "магистерская_фибула_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47299, name: "Магистерский латный шлем эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("head", "магистерский_латный_шлем_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 49582, name: "Капюшон эфенского жреца", grade: 7, iconUrl: ITEM_ICON("head", "капюшон_эфенского_жреца"), sealIconUrl: null },
  { id: 49589, name: "Треуголка эфенского искателя истины", grade: 7, iconUrl: ITEM_ICON("head", "треуголка_эфенского_искателя_истины"), sealIconUrl: null },
  { id: 49596, name: "Латный шлем эфенского стража святилища", grade: 7, iconUrl: ITEM_ICON("head", "латный_шлем_эфенского_стража_святилища"), sealIconUrl: null },
  { id: 49603, name: "Капюшон эфенского алтарника", grade: 7, iconUrl: ITEM_ICON("head", "капюшон_эфенского_алтарника"), sealIconUrl: null },
  { id: 49610, name: "Треуголка эфенского хранителя тайн", grade: 7, iconUrl: ITEM_ICON("head", "треуголка_эфенского_хранителя_тайн"), sealIconUrl: null },
  { id: 55412, name: "Капюшон проклятого жреца", grade: 12, iconUrl: ITEM_ICON("head", "капюшон_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55419, name: "Треуголка проклятого искателя истины", grade: 12, iconUrl: ITEM_ICON("head", "треуголка_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55426, name: "Латный шлем проклятого стража святилища", grade: 12, iconUrl: ITEM_ICON("head", "латный_шлем_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55433, name: "Капюшон проклятого алтарника", grade: 12, iconUrl: ITEM_ICON("head", "капюшон_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55440, name: "Треуголка проклятого хранителя тайн", grade: 12, iconUrl: ITEM_ICON("head", "треуголка_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 900001, name: "Капюшон возрожденного жреца", grade: 12, iconUrl: ITEM_ICON("head", "капюшон_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900002, name: "Треуголка возрожденного искателя истины", grade: 12, iconUrl: ITEM_ICON("head", "треуголка_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900003, name: "Латный шлем возрожденного стража святилища", grade: 12, iconUrl: ITEM_ICON("head", "латный_шлем_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900004, name: "Капюшон возрожденного алтарника", grade: 12, iconUrl: ITEM_ICON("head", "капюшон_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900005, name: "Треуголка возрожденного хранителя тайн", grade: 12, iconUrl: ITEM_ICON("head", "треуголка_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 45352, name: "Рамианский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "рамианский_латный_шлем"), sealIconUrl: null },
  { id: 45665, name: "Искаженный рамианский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "искаженный_рамианский_латный_шлем"), sealIconUrl: null },
  { id: 45858, name: "Проклятый рамианский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "проклятый_рамианский_латный_шлем"), sealIconUrl: null },
  { id: 46868, name: "Изначальный рамианский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "изначальный_рамианский_латный_шлем"), sealIconUrl: null },
  { id: 48392, name: "Обновленный рамианский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "обновленный_рамианский_латный_шлем"), sealIconUrl: null },
  { id: 53052, name: "Совершенный рамианский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "совершенный_рамианский_латный_шлем"), sealIconUrl: null },
  { id: 45345, name: "Рамианский кожаный капюшон", grade: 1, iconUrl: ITEM_ICON("head", "рамианский_кожаный_капюшон"), sealIconUrl: null },
  { id: 45658, name: "Искаженный рамианский кожаный капюшон", grade: 1, iconUrl: ITEM_ICON("head", "искаженный_рамианский_кожаный_капюшон"), sealIconUrl: null },
  { id: 45851, name: "Проклятый рамианский кожаный капюшон", grade: 1, iconUrl: ITEM_ICON("head", "проклятый_рамианский_кожаный_капюшон"), sealIconUrl: null },
  { id: 46861, name: "Изначальный рамианский кожаный шлем", grade: 1, iconUrl: ITEM_ICON("head", "изначальный_рамианский_кожаный_шлем"), sealIconUrl: null },
  { id: 48385, name: "Обновленный рамианский кожаный капюшон", grade: 1, iconUrl: ITEM_ICON("head", "обновленный_рамианский_кожаный_капюшон"), sealIconUrl: null },
  { id: 53045, name: "Совершенный рамианский кожаный капюшон", grade: 1, iconUrl: ITEM_ICON("head", "совершенный_рамианский_кожаный_капюшон"), sealIconUrl: null },
  { id: 45338, name: "Рамианская диадема", grade: 1, iconUrl: ITEM_ICON("head", "рамианская_диадема"), sealIconUrl: null },
  { id: 45651, name: "Искаженная рамианская диадема", grade: 1, iconUrl: ITEM_ICON("head", "искаженная_рамианская_диадема"), sealIconUrl: null },
  { id: 45844, name: "Проклятая рамианская диадема", grade: 1, iconUrl: ITEM_ICON("head", "проклятая_рамианская_диадема"), sealIconUrl: null },
  { id: 46854, name: "Изначальный рамианский налобник", grade: 1, iconUrl: ITEM_ICON("head", "изначальный_рамианский_налобник"), sealIconUrl: null },
  { id: 48378, name: "Обновленный рамианский налобник", grade: 1, iconUrl: ITEM_ICON("head", "обновленный_рамианский_налобник"), sealIconUrl: null },
  { id: 53038, name: "Совершенный рамианский налобник", grade: 1, iconUrl: ITEM_ICON("head", "совершенный_рамианский_налобник"), sealIconUrl: null },
  { id: 54953, name: "Эфенский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "эфенский_латный_шлем"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 54995, name: "Искаженный эфенский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "искаженный_эфенский_латный_шлем"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55038, name: "Изначальный эфенский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "изначальный_эфенский_латный_шлем"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55080, name: "Обновленный эфенский латный шлем", grade: 1, iconUrl: ITEM_ICON("head", "обновленный_эфенский_латный_шлем"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54960, name: "Эфенский кожаный шлем", grade: 1, iconUrl: ITEM_ICON("head", "эфенский_кожаный_шлем"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55002, name: "Искаженный эфенский кожаный шлем", grade: 1, iconUrl: ITEM_ICON("head", "искаженный_эфенский_кожаный_шлем"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55045, name: "Изначальный эфенский кожаный шлем", grade: 1, iconUrl: ITEM_ICON("head", "изначальный_эфенский_кожаный_шлем"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55087, name: "Обновленный эфенский кожаный шлем", grade: 1, iconUrl: ITEM_ICON("head", "обновленный_эфенский_кожаный_шлем"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54967, name: "Эфенский капюшон", grade: 1, iconUrl: ITEM_ICON("head", "эфенский_капюшон"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55009, name: "Искаженный эфенский капюшон", grade: 1, iconUrl: ITEM_ICON("head", "искаженный_эфенский_капюшон"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55052, name: "Изначальный эфенский капюшон", grade: 1, iconUrl: ITEM_ICON("head", "изначальный_эфенский_капюшон"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55094, name: "Обновленный эфенский капюшон", grade: 1, iconUrl: ITEM_ICON("head", "обновленный_эфенский_капюшон"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 48745, name: "Шлем любимца Изы", grade: 1, iconUrl: ITEM_ICON("head", "шлем_любимца_изы"), sealIconUrl: null },
  { id: 43663, name: "Капюшон иферийского советника", grade: 1, iconUrl: ITEM_ICON("head", "капюшон_иферийского_советника"), sealIconUrl: null },
  { id: 48411, name: "Шлем властелина морей", grade: 1, iconUrl: ITEM_ICON("head", "шлем_властелина_морей"), sealIconUrl: SEAL_ICON("top_leviathan") },
  { id: 49376, name: "Шлем избранника Изы", grade: 1, iconUrl: ITEM_ICON("head", "шлем_избранника_изы"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49381, name: "Капюшон иферийского визиря", grade: 1, iconUrl: ITEM_ICON("head", "капюшон_иферийского_визиря"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49371, name: "Шлем владыки морей", grade: 1, iconUrl: ITEM_ICON("head", "шлем_владыки_морей"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 20752, name: "Иферийская кожаная маска охотника", grade: 1, iconUrl: ITEM_ICON("head", "иферийская_кожаная_маска_охотника"), sealIconUrl: null },
];
