import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const LEGS_ITEMS: GearItem[] = [
  { id: 45882, name: "Матерчатые поножи эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("legs", "матерчатые_поножи_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 45889, name: "Кожаные поножи заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("legs", "кожаные_поножи_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 45989, name: "Матерчатые поножи смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("legs", "матерчатые_поножи_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 45896, name: "Латные поножи эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("legs", "латные_поножи_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 47045, name: "Кожаные поножи укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("legs", "кожаные_поножи_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47275, name: "Магистерские матерчатые поножи смотрителя тайных архивов", grade: 1, iconUrl: ITEM_ICON("legs", "магистерские_матерчатые_поножи_смотрителя_тайных_архивов"), sealIconUrl: null },
  { id: 47280, name: "Магистерские матерчатые поножи эрнардского мнемоника", grade: 1, iconUrl: ITEM_ICON("legs", "магистерские_матерчатые_поножи_эрнардского_мнемоника"), sealIconUrl: null },
  { id: 47287, name: "Магистерские кожаные поножи укротителя гримуаров", grade: 1, iconUrl: ITEM_ICON("legs", "магистерские_кожаные_поножи_укротителя_гримуаров"), sealIconUrl: null },
  { id: 47294, name: "Магистерские кожаные поножи заклинателя гримуаров", grade: 1, iconUrl: ITEM_ICON("legs", "магистерские_кожаные_поножи_заклинателя_гримуаров"), sealIconUrl: null },
  { id: 47301, name: "Магистерские латные поножи эрнардского архивариуса", grade: 1, iconUrl: ITEM_ICON("legs", "магистерские_латные_поножи_эрнардского_архивариуса"), sealIconUrl: null },
  { id: 49584, name: "Матерчатые поножи эфенского жреца", grade: 7, iconUrl: ITEM_ICON("legs", "матерчатые_поножи_эфенского_жреца"), sealIconUrl: null },
  { id: 49591, name: "Кожаные поножи эфенского искателя истины", grade: 7, iconUrl: ITEM_ICON("legs", "кожаные_поножи_эфенского_искателя_истины"), sealIconUrl: null },
  { id: 49598, name: "Латные поножи эфенского стража святилища", grade: 7, iconUrl: ITEM_ICON("legs", "латные_поножи_эфенского_стража_святилища"), sealIconUrl: null },
  { id: 49605, name: "Матерчатые поножи эфенского алтарника", grade: 7, iconUrl: ITEM_ICON("legs", "матерчатые_поножи_эфенского_алтарника"), sealIconUrl: null },
  { id: 49612, name: "Кожаные поножи эфенского хранителя тайн", grade: 7, iconUrl: ITEM_ICON("legs", "кожаные_поножи_эфенского_хранителя_тайн"), sealIconUrl: null },
  { id: 55414, name: "Матерчатые поножи проклятого жреца", grade: 12, iconUrl: ITEM_ICON("legs", "матерчатые_поножи_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55421, name: "Кожаные поножи проклятого искателя истины", grade: 12, iconUrl: ITEM_ICON("legs", "кожаные_поножи_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55428, name: "Латные поножи проклятого стража святилища", grade: 12, iconUrl: ITEM_ICON("legs", "латные_поножи_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55435, name: "Матерчатые поножи проклятого алтарника", grade: 12, iconUrl: ITEM_ICON("legs", "матерчатые_поножи_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 55442, name: "Кожаные поножи проклятого хранителя тайн", grade: 12, iconUrl: ITEM_ICON("legs", "кожаные_поножи_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_spike") },
  { id: 900026, name: "Матерчатые поножи возрожденного жреца", grade: 12, iconUrl: ITEM_ICON("legs", "матерчатые_поножи_проклятого_жреца"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900027, name: "Кожаные поножи возрожденного искателя истины", grade: 12, iconUrl: ITEM_ICON("legs", "кожаные_поножи_проклятого_искателя_истины"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900028, name: "Латные поножи возрожденного стража святилища", grade: 12, iconUrl: ITEM_ICON("legs", "латные_поножи_проклятого_стража_святилища"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900029, name: "Матерчатые поножи возрожденного алтарника", grade: 12, iconUrl: ITEM_ICON("legs", "матерчатые_поножи_проклятого_алтарника"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 900030, name: "Кожаные поножи возрожденного хранителя тайн", grade: 12, iconUrl: ITEM_ICON("legs", "кожаные_поножи_проклятого_хранителя_тайн"), sealIconUrl: SEAL_ICON("top_thiol_2") },
  { id: 45354, name: "Рамианские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "рамианские_латные_поножи"), sealIconUrl: null },
  { id: 45667, name: "Искаженные рамианские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "искаженные_рамианские_латные_поножи"), sealIconUrl: null },
  { id: 45860, name: "Проклятые рамианские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "проклятые_рамианские_латные_поножи"), sealIconUrl: null },
  { id: 46870, name: "Изначальные рамианские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "изначальные_рамианские_латные_поножи"), sealIconUrl: null },
  { id: 48394, name: "Обновленные рамианские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "обновленные_рамианские_латные_поножи"), sealIconUrl: null },
  { id: 53054, name: "Совершенные рамианские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "совершенные_рамианские_латные_поножи"), sealIconUrl: null },
  { id: 45347, name: "Рамианские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "рамианские_кожаные_поножи"), sealIconUrl: null },
  { id: 45660, name: "Искаженные рамианские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "искаженные_рамианские_кожаные_поножи"), sealIconUrl: null },
  { id: 45853, name: "Проклятые рамианские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "проклятые_рамианские_кожаные_поножи"), sealIconUrl: null },
  { id: 46863, name: "Изначальные рамианские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "изначальные_рамианские_кожаные_поножи"), sealIconUrl: null },
  { id: 48387, name: "Обновленные рамианские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "обновленные_рамианские_кожаные_поножи"), sealIconUrl: null },
  { id: 53047, name: "Совершенные рамианские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "совершенные_рамианские_кожаные_поножи"), sealIconUrl: null },
  { id: 45340, name: "Рамианские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "рамианские_матерчатые_поножи"), sealIconUrl: null },
  { id: 45653, name: "Искаженные рамианские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "искаженные_рамианские_матерчатые_поножи"), sealIconUrl: null },
  { id: 45846, name: "Проклятые рамианские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "проклятые_рамианские_матерчатые_поножи"), sealIconUrl: null },
  { id: 46856, name: "Изначальные рамианские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "изначальные_рамианские_матерчатые_поножи"), sealIconUrl: null },
  { id: 48380, name: "Обновленные рамианские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "обновленные_рамианские_матерчатые_поножи"), sealIconUrl: null },
  { id: 53040, name: "Совершенные рамианские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "совершенные_рамианские_матерчатые_поножи"), sealIconUrl: null },
  { id: 54955, name: "Эфенские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "эфенские_латные_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 54997, name: "Искаженные эфенские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "искаженные_эфенские_латные_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55040, name: "Изначальные эфенские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "изначальные_эфенские_латные_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55082, name: "Обновленные эфенские латные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "обновленные_эфенские_латные_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54962, name: "Эфенские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "эфенские_кожаные_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55004, name: "Искаженные эфенские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "искаженные_эфенские_кожаные_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55047, name: "Изначальные эфенские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "изначальные_эфенские_кожаные_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55089, name: "Обновленные эфенские кожаные поножи", grade: 1, iconUrl: ITEM_ICON("legs", "обновленные_эфенские_кожаные_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 54969, name: "Эфенские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "эфенские_матерчатые_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55011, name: "Искаженные эфенские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "искаженные_эфенские_матерчатые_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55054, name: "Изначальные эфенские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "изначальные_эфенские_матерчатые_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55096, name: "Обновленные эфенские матерчатые поножи", grade: 1, iconUrl: ITEM_ICON("legs", "обновленные_эфенские_матерчатые_поножи"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 48747, name: "Поножи любимца Изы", grade: 1, iconUrl: ITEM_ICON("legs", "поножи_любимца_изы"), sealIconUrl: null },
  { id: 43668, name: "Поножи иферийского советника", grade: 1, iconUrl: ITEM_ICON("legs", "поножи_иферийского_советника"), sealIconUrl: null },
  { id: 48413, name: "Поножи властелина морей", grade: 1, iconUrl: ITEM_ICON("legs", "поножи_властелина_морей"), sealIconUrl: SEAL_ICON("top_leviathan") },
  { id: 49378, name: "Поножи избранника Изы", grade: 1, iconUrl: ITEM_ICON("legs", "поножи_избранника_изы"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49385, name: "Поножи иферийского визиря", grade: 1, iconUrl: ITEM_ICON("legs", "поножи_иферийского_визиря"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 49373, name: "Поножи владыки морей", grade: 1, iconUrl: ITEM_ICON("legs", "поножи_владыки_морей"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 20806, name: "Иферийские кожаные поножи охотника", grade: 1, iconUrl: ITEM_ICON("legs", "иферийские_кожаные_поножи_охотника"), sealIconUrl: null },
];
