import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const NECKLACE_ITEMS: GearItem[] = [
  { id: 29731, name: "Ожерелье доблести I ранга", grade: 1, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_i_ранга"), sealIconUrl: null },
  { id: 29743, name: "Ожерелье доблести II ранга", grade: 2, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_ii_ранга"), sealIconUrl: null },
  { id: 29744, name: "Ожерелье доблести III ранга", grade: 2, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_iii_ранга"), sealIconUrl: null },
  { id: 29745, name: "Ожерелье доблести IV ранга", grade: 3, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_iv_ранга"), sealIconUrl: null },
  { id: 29746, name: "Ожерелье доблести V ранга", grade: 3, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_v_ранга"), sealIconUrl: null },
  { id: 29747, name: "Ожерелье доблести VI ранга", grade: 4, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_vi_ранга"), sealIconUrl: null },
  { id: 29748, name: "Ожерелье доблести воина VII ранга", grade: 5, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_воина_vii_ранга"), sealIconUrl: null },
  { id: 29749, name: "Ожерелье доблести воина VIII ранга", grade: 6, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_воина_viii_ранга"), sealIconUrl: null },
  { id: 29750, name: "Ожерелье доблести воина IX ранга", grade: 7, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_воина_ix_ранга"), sealIconUrl: null },
  { id: 29751, name: "Ожерелье доблести воина X ранга", grade: 8, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_воина_x_ранга"), sealIconUrl: null },
  { id: 37908, name: "Ожерелье доблести воина XI ранга", grade: 9, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_воина_xi_ранга"), sealIconUrl: null },
  { id: 37909, name: "Ожерелье доблести воина XII ранга", grade: 10, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_воина_xii_ранга"), sealIconUrl: null },
  { id: 40366, name: "Ожерелье доблести воина XIII ранга", grade: 11, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_воина_xiii_ранга"), sealIconUrl: null },
  { id: 40477, name: "Ожерелье доблести целителя VII ранга", grade: 5, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_целителя_vii_ранга"), sealIconUrl: null },
  { id: 40478, name: "Ожерелье доблести целителя VIII ранга", grade: 6, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_целителя_viii_ранга"), sealIconUrl: null },
  { id: 40479, name: "Ожерелье доблести целителя IX ранга", grade: 7, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_целителя_ix_ранга"), sealIconUrl: null },
  { id: 40480, name: "Ожерелье доблести целителя X ранга", grade: 8, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_целителя_x_ранга"), sealIconUrl: null },
  { id: 40481, name: "Ожерелье доблести целителя XI ранга", grade: 9, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_целителя_xi_ранга"), sealIconUrl: null },
  { id: 40482, name: "Ожерелье доблести целителя XII ранга", grade: 10, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_целителя_xii_ранга"), sealIconUrl: null },
  { id: 40483, name: "Ожерелье доблести целителя XIII ранга", grade: 11, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_целителя_xiii_ранга"), sealIconUrl: null },
  { id: 44634, name: "Ожерелье доблести воина XIV ранга", grade: 12, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_воина_xiv_ранга"), sealIconUrl: null },
  { id: 44635, name: "Ожерелье доблести целителя XIV ранга", grade: 12, iconUrl: ITEM_ICON("necklace", "ожерелье_доблести_целителя_xiv_ранга"), sealIconUrl: null },
  { id: 48601, name: "Ожерелье проводника", grade: 1, iconUrl: ITEM_ICON("necklace", "ожерелье_проводника"), sealIconUrl: null },
  { id: 48603, name: "Ожерелье последнего рубежа", grade: 1, iconUrl: ITEM_ICON("necklace", "ожерелье_последнего_рубежа"), sealIconUrl: null },
  { id: 35409, name: "Иферийское ожерелье авантюриста", grade: 1, iconUrl: ITEM_ICON("necklace", "иферийское_ожерелье_авантюриста"), sealIconUrl: null },
  { id: 35410, name: "Иферийское ожерелье магистра", grade: 1, iconUrl: ITEM_ICON("necklace", "иферийское_ожерелье_магистра"), sealIconUrl: null },
  { id: 31638, name: "Иферийское ожерелье мудреца", grade: 1, iconUrl: ITEM_ICON("necklace", "иферийское_ожерелье_мудреца"), sealIconUrl: null },
  { id: 31635, name: "Иферийское ожерелье наемника", grade: 1, iconUrl: ITEM_ICON("necklace", "иферийское_ожерелье_наемника"), sealIconUrl: null },
  { id: 31637, name: "Иферийское ожерелье охотника", grade: 1, iconUrl: ITEM_ICON("necklace", "иферийское_ожерелье_охотника"), sealIconUrl: null },
  { id: 31634, name: "Иферийское ожерелье хранителя", grade: 1, iconUrl: ITEM_ICON("necklace", "иферийское_ожерелье_хранителя"), sealIconUrl: null },
  { id: 31636, name: "Иферийское ожерелье целителя", grade: 1, iconUrl: ITEM_ICON("necklace", "иферийское_ожерелье_целителя"), sealIconUrl: null },
];
