import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const WEAPON_RANGED_ITEMS: GearItem[] = [
  { id: 45334, name: "Рамианский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "рамианский_лук"), sealIconUrl: null },
  { id: 45646, name: "Искаженный рамианский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "искаженный_рамианский_лук"), sealIconUrl: null },
  { id: 45839, name: "Проклятый рамианский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "проклятый_рамианский_лук"), sealIconUrl: null },
  { id: 46849, name: "Изначальный рамианский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "изначальный_рамианский_лук"), sealIconUrl: null },
  { id: 48373, name: "Обновленный рамианский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "обновленный_рамианский_лук"), sealIconUrl: null },
  { id: 53032, name: "Совершенный рамианский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "совершенный_рамианский_лук"), sealIconUrl: null },
  { id: 54987, name: "Эфенский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "эфенский_лук"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55029, name: "Искаженный эфенский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "искаженный_эфенский_лук"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55072, name: "Изначальный эфенский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "изначальный_эфенский_лук"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55114, name: "Обновленный эфенский лук", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "обновленный_эфенский_лук"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 50836, name: "Рамианская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "рамианская_винтовка"), sealIconUrl: null },
  { id: 50837, name: "Искаженная рамианская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "искаженная_рамианская_винтовка"), sealIconUrl: null },
  { id: 50838, name: "Проклятая рамианская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "проклятая_рамианская_винтовка"), sealIconUrl: null },
  { id: 50839, name: "Изначальная рамианская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "изначальная_рамианская_винтовка"), sealIconUrl: null },
  { id: 50840, name: "Обновленная рамианская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "обновленная_рамианская_винтовка"), sealIconUrl: null },
  { id: 53037, name: "Совершенная рамианская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "совершенная_рамианская_винтовка"), sealIconUrl: null },
  { id: 54994, name: "Эфенская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "эфенская_винтовка"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55037, name: "Искаженная эфенская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "искаженная_эфенская_винтовка"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55079, name: "Изначальная эфенская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "изначальная_эфенская_винтовка"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55121, name: "Обновленная эфенская винтовка", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "обновленная_эфенская_винтовка"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 28896, name: "Алый лук из драконьей кости", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "алый_лук_из_драконьей_кости"), sealIconUrl: null },
  { id: 28897, name: "Пламенеющий лук из драконьей кости", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "пламенеющий_лук_из_драконьей_кости"), sealIconUrl: null },
  { id: 45301, name: "Иг'нис, Пламя возмездия", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "игнис_пламя_возмездия"), sealIconUrl: null },
  { id: 49367, name: "Иг'нис, Пробужденное пламя", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "игнис_пробужденное_пламя"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 50868, name: "Джераб, слуга смерти", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "джераб_слуга_смерти"), sealIconUrl: null },
  { id: 51164, name: "Укрепленная Джераб, слуга смерти", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "укрепленная_джераб_слуга_смерти"), sealIconUrl: SEAL_ICON("top_obsidian") },
  { id: 50847, name: "Алая винтовка охотника на драконов", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "алая_винтовка_охотника_на_драконов"), sealIconUrl: null },
  { id: 50848, name: "Пламенеющая винтовка охотника на драконов", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "пламенеющая_винтовка_охотника_на_драконов"), sealIconUrl: null },
  { id: 50849, name: "Дра'орис, Дыхание дракона", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "драорис_дыхание_дракона"), sealIconUrl: null },
  { id: 51169, name: "Дра'орис, Пробужденное разрушение", grade: 1, iconUrl: ITEM_ICON("weapon_ranged", "драорис_пробужденное_разрушение"), sealIconUrl: SEAL_ICON("top_fire") },
];
