import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const WEAPON_MAIN_ITEMS: GearItem[] = [
  { id: 55111, name: "Обновленная эфенская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленная_эфенская_алебарда"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 55069, name: "Изначальная эфенская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальная_эфенская_алебарда"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55026, name: "Искаженная эфенская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженная_эфенская_алебарда"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 54984, name: "Эфенская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенская_алебарда"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 53028, name: "Совершенная рамианская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенная_рамианская_алебарда"), sealIconUrl: null },
  { id: 48370, name: "Обновленная рамианская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленная_рамианская_алебарда"), sealIconUrl: null },
  { id: 46846, name: "Изначальная рамианская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальная_рамианская_алебарда"), sealIconUrl: null },
  { id: 45836, name: "Проклятая рамианская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятая_рамианская_алебарда"), sealIconUrl: null },
  { id: 45643, name: "Искаженная рамианская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженная_рамианская_алебарда"), sealIconUrl: null },
  { id: 45331, name: "Рамианская алебарда", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианская_алебарда"), sealIconUrl: null },
  { id: 55103, name: "Обновленный эфенский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_эфенский_клеймор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 55061, name: "Изначальный эфенский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_эфенский_клеймор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55018, name: "Искаженный эфенский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_эфенский_клеймор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 54976, name: "Эфенский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенский_клеймор"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 53020, name: "Совершенный рамианский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_клеймор"), sealIconUrl: null },
  { id: 48362, name: "Обновленный рамианский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_клеймор"), sealIconUrl: null },
  { id: 46838, name: "Изначальный рамианский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_клеймор"), sealIconUrl: null },
  { id: 45828, name: "Проклятый рамианский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_клеймор"), sealIconUrl: null },
  { id: 45635, name: "Искаженный рамианский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_клеймор"), sealIconUrl: null },
  { id: 45323, name: "Рамианский клеймор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_клеймор"), sealIconUrl: null },
  { id: 50276, name: "Ишхар, грань измерений", grade: 1, iconUrl: ITEM_ICON("weapon_main", "ишхар_грань_измерений"), sealIconUrl: null },
  { id: 50330, name: "Укрепленный Ишхар, грань измерений", grade: 1, iconUrl: ITEM_ICON("weapon_main", "укрепленный_ишхар_грань_измерений"), sealIconUrl: SEAL_ICON("top_obsidian") },
  { id: 55105, name: "Обновленный эфенский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_эфенский_палаш"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 55063, name: "Изначальный эфенский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_эфенский_палаш"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55020, name: "Искаженный эфенский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_эфенский_палаш"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 54978, name: "Эфенский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенский_палаш"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 53022, name: "Совершенный рамианский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_палаш"), sealIconUrl: null },
  { id: 48364, name: "Обновленный рамианский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_палаш"), sealIconUrl: null },
  { id: 46840, name: "Изначальный рамианский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_палаш"), sealIconUrl: null },
  { id: 45830, name: "Проклятый рамианский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_палаш"), sealIconUrl: null },
  { id: 45637, name: "Искаженный рамианский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_палаш"), sealIconUrl: null },
  { id: 45325, name: "Рамианский палаш", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_палаш"), sealIconUrl: null },
  { id: 49368, name: "Мор'гур, Пробужденная смерть", grade: 1, iconUrl: ITEM_ICON("weapon_main", "моргур_пробужденная_смерть"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 45302, name: "Мор'гур, Смерть драконов", grade: 1, iconUrl: ITEM_ICON("weapon_main", "моргур_смерть_драконов"), sealIconUrl: null },
  { id: 55107, name: "Обновленная эфенская секира", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленная_эфенская_секира"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 55065, name: "Изначальная эфенская секира", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальная_эфенская_секира"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55022, name: "Искаженная эфенская секира", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженная_эфенская_секира"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 54980, name: "Эфенская секира", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенская_секира"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 53024, name: "Совершенный рамианский лабрис", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_лабрис"), sealIconUrl: null },
  { id: 48366, name: "Обновленный рамианский лабрис", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_лабрис"), sealIconUrl: null },
  { id: 46842, name: "Изначальный рамианский лабрис", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_лабрис"), sealIconUrl: null },
  { id: 45832, name: "Проклятый рамианский лабрис", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_лабрис"), sealIconUrl: null },
  { id: 45639, name: "Искаженный рамианский лабрис", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_лабрис"), sealIconUrl: null },
  { id: 45327, name: "Рамианский лабрис", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_лабрис"), sealIconUrl: null },
  { id: 50332, name: "Закаленный Гирра, пробивающий брешь", grade: 1, iconUrl: ITEM_ICON("weapon_main", "закаленный_гирра_пробивающий_брешь"), sealIconUrl: SEAL_ICON("top_obsidian") },
  { id: 50278, name: "Гирра, пробивающий брешь", grade: 1, iconUrl: ITEM_ICON("weapon_main", "гирра_пробивающий_брешь"), sealIconUrl: null },
  { id: 55109, name: "Обновленный эфенский боевой молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_эфенский_боевой_молот"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 55067, name: "Изначальный эфенский боевой молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_эфенский_боевой_молот"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55024, name: "Искаженный эфенский боевой молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_эфенский_боевой_молот"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 54982, name: "Эфенский боевой молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенский_боевой_молот"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 53026, name: "Совершенный рамианский боевой молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_боевой_молот"), sealIconUrl: null },
  { id: 48368, name: "Обновленный рамианский боевой молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_боевой_молот"), sealIconUrl: null },
  { id: 46844, name: "Изначальный рамианский молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_молот"), sealIconUrl: null },
  { id: 45834, name: "Проклятый рамианский молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_молот"), sealIconUrl: null },
  { id: 45641, name: "Искаженный рамианский молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_молот"), sealIconUrl: null },
  { id: 45329, name: "Рамианский молот", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_молот"), sealIconUrl: null },
  { id: 55113, name: "Обновленный эфенский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_эфенский_боевой_посох"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 55071, name: "Изначальный эфенский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_эфенский_боевой_посох"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55028, name: "Искаженный эфенский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_эфенский_боевой_посох"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 54986, name: "Эфенский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенский_боевой_посох"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 53031, name: "Совершенный рамианский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_боевой_посох"), sealIconUrl: null },
  { id: 48372, name: "Обновленный рамианский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_боевой_посох"), sealIconUrl: null },
  { id: 46848, name: "Изначальный рамианский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_боевой_посох"), sealIconUrl: null },
  { id: 45838, name: "Проклятый рамианский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_боевой_посох"), sealIconUrl: null },
  { id: 45645, name: "Искаженный рамианский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_боевой_посох"), sealIconUrl: null },
  { id: 45333, name: "Рамианский боевой посох", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_боевой_посох"), sealIconUrl: null },
  { id: 49369, name: "Вул'данор, Пробужденная тьма", grade: 1, iconUrl: ITEM_ICON("weapon_main", "вулданор_пробужденная_тьма"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 45303, name: "Вул'данор, Клеймитель драконов", grade: 1, iconUrl: ITEM_ICON("weapon_main", "вулданор_клеймитель_драконов"), sealIconUrl: null },
  { id: 45907, name: "Окаменевшая эрнардская палица", grade: 1, iconUrl: ITEM_ICON("weapon_main", "окаменевшая_эрнардская_палица"), sealIconUrl: null },
  { id: 47270, name: "Магистерская окаменевшая эрнардская палица", grade: 1, iconUrl: ITEM_ICON("weapon_main", "магистерская_окаменевшая_эрнардская_палица"), sealIconUrl: null },
  { id: 49577, name: "Позолоченная палица хранителя священной рощи", grade: 1, iconUrl: ITEM_ICON("weapon_main", "позолоченная_палица_хранителя_священной_рощи"), sealIconUrl: null },
  { id: 54974, name: "Эфенский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенский_кинжал"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55016, name: "Искаженный эфенский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_эфенский_кинжал"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55059, name: "Изначальный эфенский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_эфенский_кинжал"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55101, name: "Обновленный эфенский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_эфенский_кинжал"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45321, name: "Рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_кинжал"), sealIconUrl: null },
  { id: 45633, name: "Искаженный рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_кинжал"), sealIconUrl: null },
  { id: 45826, name: "Проклятый рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_кинжал"), sealIconUrl: null },
  { id: 46836, name: "Изначальный рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_кинжал"), sealIconUrl: null },
  { id: 48360, name: "Обновленный рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_кинжал"), sealIconUrl: null },
  { id: 53018, name: "Совершенный рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_кинжал"), sealIconUrl: null },
  { id: 54975, name: "Эфенский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенский_меч"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55017, name: "Искаженный эфенский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_эфенский_меч"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55060, name: "Изначальный эфенский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_эфенский_меч"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55102, name: "Обновленный эфенский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_эфенский_меч"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45322, name: "Рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_меч"), sealIconUrl: null },
  { id: 45634, name: "Искаженный рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_меч"), sealIconUrl: null },
  { id: 45827, name: "Проклятый рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_меч"), sealIconUrl: null },
  { id: 46837, name: "Изначальный рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_меч"), sealIconUrl: null },
  { id: 48361, name: "Обновленный рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_меч"), sealIconUrl: null },
  { id: 53019, name: "Совершенный рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_меч"), sealIconUrl: null },
  { id: 45299, name: "Рави'мар, Драконья ярость", grade: 1, iconUrl: ITEM_ICON("weapon_main", "равимар_драконья_ярость"), sealIconUrl: null },
  { id: 49365, name: "Рави'мар, Пробужденный гнев", grade: 1, iconUrl: ITEM_ICON("weapon_main", "равимар_пробужденный_гнев"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 54977, name: "Эфенский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенский_ятаган"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55019, name: "Искаженный эфенский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_эфенский_ятаган"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55062, name: "Изначальный эфенский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_эфенский_ятаган"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55104, name: "Обновленный эфенский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_эфенский_ятаган"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45324, name: "Рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_ятаган"), sealIconUrl: null },
  { id: 45636, name: "Искаженный рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_ятаган"), sealIconUrl: null },
  { id: 45829, name: "Проклятый рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_ятаган"), sealIconUrl: null },
  { id: 46839, name: "Изначальный рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_ятаган"), sealIconUrl: null },
  { id: 48363, name: "Обновленный рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_ятаган"), sealIconUrl: null },
  { id: 53021, name: "Совершенный рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_ятаган"), sealIconUrl: null },
  { id: 50277, name: "Ташш, змеиное жало", grade: 1, iconUrl: ITEM_ICON("weapon_main", "ташш_змеиное_жало"), sealIconUrl: null },
  { id: 50331, name: "Закаленный Ташш, змеиное жало", grade: 1, iconUrl: ITEM_ICON("weapon_main", "закаленный_ташш_змеиное_жало"), sealIconUrl: SEAL_ICON("top_obsidian") },
  { id: 54979, name: "Эфенский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "эфенский_боевой_топор"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55021, name: "Искаженный эфенский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_эфенский_боевой_топор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55064, name: "Изначальный эфенский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_эфенский_боевой_топор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55106, name: "Обновленный эфенский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_эфенский_боевой_топор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45326, name: "Рамианский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "рамианский_боевой_топор"), sealIconUrl: null },
  { id: 45638, name: "Искаженный рамианский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "искаженный_рамианский_боевой_топор"), sealIconUrl: null },
  { id: 45831, name: "Проклятый рамианский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "проклятый_рамианский_боевой_топор"), sealIconUrl: null },
  { id: 46841, name: "Изначальный рамианский топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "изначальный_рамианский_топор"), sealIconUrl: null },
  { id: 48365, name: "Обновленный рамианский топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "обновленный_рамианский_топор"), sealIconUrl: null },
  { id: 53023, name: "Совершенный рамианский топор", grade: 1, iconUrl: ITEM_ICON("weapon_main", "совершенный_рамианский_топор"), sealIconUrl: null },
  { id: 43073, name: "Пламенеющий Нарвиг", grade: 1, iconUrl: ITEM_ICON("weapon_main", "пламенеющий_нарвиг"), sealIconUrl: null },
  { id: 50340, name: "Нарвиг, повелевающий пламенем", grade: 1, iconUrl: ITEM_ICON("weapon_main", "нарвиг_повелевающий_пламенем"), sealIconUrl: null },
  { id: 18661, name: "Нарвиг, огненный клинок Морфеоса", grade: 1, iconUrl: ITEM_ICON("weapon_main", "нарвиг_огненный_клинок_морфеоса"), sealIconUrl: null },
];
