import type { GearItem } from "./types";
import { ITEM_ICON, SEAL_ICON } from "./paths";

export const WEAPON_OFF_ITEMS: GearItem[] = [
  { id: 54988, name: "Эфенский щит", grade: 1, iconUrl: ITEM_ICON("weapon_off", "эфенский_щит"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55030, name: "Искаженный эфенский щит", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_эфенский_щит"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55073, name: "Изначальный эфенский щит", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_эфенский_щит"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55115, name: "Обновленный эфенский щит", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_эфенский_щит"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45337, name: "Рамианский щит стража", grade: 1, iconUrl: ITEM_ICON("weapon_off", "рамианский_щит_стража"), sealIconUrl: null },
  { id: 45480, name: "Рамианский щит заклинателя", grade: 1, iconUrl: ITEM_ICON("weapon_off", "рамианский_щит_заклинателя"), sealIconUrl: null },
  { id: 45649, name: "Искаженный рамианский щит стража", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_рамианский_щит_стража"), sealIconUrl: null },
  { id: 45650, name: "Искаженный рамианский щит заклинателя", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_рамианский_щит_заклинателя"), sealIconUrl: null },
  { id: 45842, name: "Проклятый рамианский щит стража", grade: 1, iconUrl: ITEM_ICON("weapon_off", "проклятый_рамианский_щит_стража"), sealIconUrl: null },
  { id: 45843, name: "Проклятый рамианский щит заклинателя", grade: 1, iconUrl: ITEM_ICON("weapon_off", "проклятый_рамианский_щит_заклинателя"), sealIconUrl: null },
  { id: 46852, name: "Изначальный рамианский щит стража", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_рамианский_щит_стража"), sealIconUrl: null },
  { id: 46853, name: "Изначальный рамианский щит заклинателя", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_рамианский_щит_заклинателя"), sealIconUrl: null },
  { id: 48376, name: "Обновленный рамианский щит стража", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_рамианский_щит_стража"), sealIconUrl: null },
  { id: 48377, name: "Обновленный рамианский щит заклинателя", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_рамианский_щит_заклинателя"), sealIconUrl: null },
  { id: 53035, name: "Совершенный рамианский щит стража", grade: 1, iconUrl: ITEM_ICON("weapon_off", "совершенный_рамианский_щит_стража"), sealIconUrl: null },
  { id: 53036, name: "Совершенный рамианский щит заклинателя", grade: 1, iconUrl: ITEM_ICON("weapon_off", "совершенный_рамианский_щит_заклинателя"), sealIconUrl: null },
  { id: 50280, name: "Нерхал, бронзовая чешуя", grade: 1, iconUrl: ITEM_ICON("weapon_off", "нерхал_бронзовая_чешуя"), sealIconUrl: null },
  { id: 50334, name: "Укрепленный Нерхал, бронзовая чешуя", grade: 1, iconUrl: ITEM_ICON("weapon_off", "укрепленный_нерхал_бронзовая_чешуя"), sealIconUrl: SEAL_ICON("top_obsidian") },
  { id: 45300, name: "Драго'ран, Гнев Гартарейн", grade: 1, iconUrl: ITEM_ICON("weapon_off", "драгоран_гнев_гартарейн"), sealIconUrl: null },
  { id: 49366, name: "Драго'ран, Пробужденная ярость", grade: 1, iconUrl: ITEM_ICON("weapon_off", "драгоран_пробужденная_ярость"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 45879, name: "Щит эрнардского чароманта", grade: 1, iconUrl: ITEM_ICON("weapon_off", "щит_эрнардского_чароманта"), sealIconUrl: null },
  { id: 47269, name: "Магистерский щит эрнардского чароманта", grade: 1, iconUrl: ITEM_ICON("weapon_off", "магистерский_щит_эрнардского_чароманта"), sealIconUrl: null },
  { id: 49581, name: "Позолоченный щит стража вечности", grade: 1, iconUrl: ITEM_ICON("weapon_off", "позолоченный_щит_стража_вечности"), sealIconUrl: null },
  { id: 54974, name: "Эфенский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "эфенский_кинжал"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55016, name: "Искаженный эфенский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_эфенский_кинжал"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55059, name: "Изначальный эфенский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_эфенский_кинжал"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55101, name: "Обновленный эфенский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_эфенский_кинжал"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45321, name: "Рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "рамианский_кинжал"), sealIconUrl: null },
  { id: 45633, name: "Искаженный рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_рамианский_кинжал"), sealIconUrl: null },
  { id: 45826, name: "Проклятый рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "проклятый_рамианский_кинжал"), sealIconUrl: null },
  { id: 46836, name: "Изначальный рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_рамианский_кинжал"), sealIconUrl: null },
  { id: 48360, name: "Обновленный рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_рамианский_кинжал"), sealIconUrl: null },
  { id: 53018, name: "Совершенный рамианский кинжал", grade: 1, iconUrl: ITEM_ICON("weapon_off", "совершенный_рамианский_кинжал"), sealIconUrl: null },
  { id: 54975, name: "Эфенский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "эфенский_меч"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55017, name: "Искаженный эфенский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_эфенский_меч"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55060, name: "Изначальный эфенский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_эфенский_меч"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55102, name: "Обновленный эфенский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_эфенский_меч"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45322, name: "Рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "рамианский_меч"), sealIconUrl: null },
  { id: 45634, name: "Искаженный рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_рамианский_меч"), sealIconUrl: null },
  { id: 45827, name: "Проклятый рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "проклятый_рамианский_меч"), sealIconUrl: null },
  { id: 46837, name: "Изначальный рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_рамианский_меч"), sealIconUrl: null },
  { id: 48361, name: "Обновленный рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_рамианский_меч"), sealIconUrl: null },
  { id: 53019, name: "Совершенный рамианский меч", grade: 1, iconUrl: ITEM_ICON("weapon_off", "совершенный_рамианский_меч"), sealIconUrl: null },
  { id: 45299, name: "Рави'мар, Драконья ярость", grade: 1, iconUrl: ITEM_ICON("weapon_off", "равимар_драконья_ярость"), sealIconUrl: null },
  { id: 49365, name: "Рави'мар, Пробужденный гнев", grade: 1, iconUrl: ITEM_ICON("weapon_off", "равимар_пробужденный_гнев"), sealIconUrl: SEAL_ICON("top_fire") },
  { id: 54977, name: "Эфенский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "эфенский_ятаган"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55019, name: "Искаженный эфенский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_эфенский_ятаган"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55062, name: "Изначальный эфенский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_эфенский_ятаган"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55104, name: "Обновленный эфенский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_эфенский_ятаган"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45324, name: "Рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "рамианский_ятаган"), sealIconUrl: null },
  { id: 45636, name: "Искаженный рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_рамианский_ятаган"), sealIconUrl: null },
  { id: 45829, name: "Проклятый рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "проклятый_рамианский_ятаган"), sealIconUrl: null },
  { id: 46839, name: "Изначальный рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_рамианский_ятаган"), sealIconUrl: null },
  { id: 48363, name: "Обновленный рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_рамианский_ятаган"), sealIconUrl: null },
  { id: 53021, name: "Совершенный рамианский ятаган", grade: 1, iconUrl: ITEM_ICON("weapon_off", "совершенный_рамианский_ятаган"), sealIconUrl: null },
  { id: 50277, name: "Ташш, змеиное жало", grade: 1, iconUrl: ITEM_ICON("weapon_off", "ташш_змеиное_жало"), sealIconUrl: null },
  { id: 50331, name: "Закаленный Ташш, змеиное жало", grade: 1, iconUrl: ITEM_ICON("weapon_off", "закаленный_ташш_змеиное_жало"), sealIconUrl: SEAL_ICON("top_obsidian") },
  { id: 54979, name: "Эфенский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "эфенский_боевой_топор"), sealIconUrl: SEAL_ICON("top_seal_ipnir") },
  { id: 55021, name: "Искаженный эфенский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_эфенский_боевой_топор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_2") },
  { id: 55064, name: "Изначальный эфенский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_эфенский_боевой_топор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_3") },
  { id: 55106, name: "Обновленный эфенский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_эфенский_боевой_топор"), sealIconUrl: SEAL_ICON("top_seal_ipnir_4") },
  { id: 45326, name: "Рамианский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "рамианский_боевой_топор"), sealIconUrl: null },
  { id: 45638, name: "Искаженный рамианский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "искаженный_рамианский_боевой_топор"), sealIconUrl: null },
  { id: 45831, name: "Проклятый рамианский боевой топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "проклятый_рамианский_боевой_топор"), sealIconUrl: null },
  { id: 46841, name: "Изначальный рамианский топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "изначальный_рамианский_топор"), sealIconUrl: null },
  { id: 48365, name: "Обновленный рамианский топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "обновленный_рамианский_топор"), sealIconUrl: null },
  { id: 53023, name: "Совершенный рамианский топор", grade: 1, iconUrl: ITEM_ICON("weapon_off", "совершенный_рамианский_топор"), sealIconUrl: null },
  { id: 43073, name: "Пламенеющий Нарвиг", grade: 1, iconUrl: ITEM_ICON("weapon_off", "пламенеющий_нарвиг"), sealIconUrl: null },
  { id: 50340, name: "Нарвиг, повелевающий пламенем", grade: 1, iconUrl: ITEM_ICON("weapon_off", "нарвиг_повелевающий_пламенем"), sealIconUrl: null },
  { id: 18661, name: "Нарвиг, огненный клинок Морфеоса", grade: 1, iconUrl: ITEM_ICON("weapon_off", "нарвиг_огненный_клинок_морфеоса"), sealIconUrl: null },
];
